/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type {
  DeleteCalendarV1CalendarsUserIdCalendarId200,
  DeleteCalendarV1SchedulesScheduleId200,
  DeleteCalendarV1SlotsSlotId200,
  DeleteNotesV1NoteId200,
  DeletePinsV1BoardsBoardId200,
  DeletePinsV1BoardsBoardIdAnchorsPinId200,
  DeletePinsV1PinsPinId200,
  DeletePinsV1TagsTagId200,
  DeleteTagsV1Tag200,
  DeleteTasksV1TaskId200,
  DeleteWorkspacesV1WorkspaceId200,
  GetAuthV1Me200,
  GetBlogV1Drafts200Item,
  GetBlogV1Posts200Item,
  GetCalendarV1CalendarsUserId200Item,
  GetCalendarV1CalendarsUserIdCalendarId200,
  GetCalendarV1CalendarsUserIdDefault200,
  GetCalendarV1EventsUserId200Item,
  GetCalendarV1EventsUserIdParams,
  GetCalendarV1EventsUserIdType200Item,
  GetCalendarV1SchedulesUserId200Item,
  GetCalendarV1SchedulesUserIdAvailability200,
  GetCalendarV1SchedulesUserIdAvailabilityParams,
  GetCalendarV1Slots200Item,
  GetCalendarV1SlotsParams,
  GetCalendarV1SlotsSlotId200,
  GetLinkV1Id200,
  GetNewsV1200Item,
  GetNewsV1ContentId200,
  GetNewsV1Params,
  GetNewsV1Recent200Item,
  GetNewsV1Search200Item,
  GetNewsV1SearchParams,
  GetNotesV1200Item,
  GetNotesV1NoteId200,
  GetNotesV1Params,
  GetPinsV1BoardsAll200Item,
  GetPinsV1BoardsAllParams,
  GetPinsV1BoardsBoardId200,
  GetPinsV1BoardsBoardIdAnchors200Item,
  GetPinsV1BoardsBoardIdPins200Item,
  GetPinsV1PinsAll200Item,
  GetPinsV1PinsAllParams,
  GetPinsV1PinsPinId200,
  GetPinsV1PinsPinIdAnchor200,
  GetPinsV1PinsPinIdSimilar200Item,
  GetPinsV1PinsRecommendations200Item,
  GetPinsV1PinsSearch200Item,
  GetPinsV1PinsSearchParams,
  GetPinsV1TagsAll200Item,
  GetPinsV1TagsAllParams,
  GetPinsV1TagsSearch200Item,
  GetPinsV1TagsSearchParams,
  GetPinsV1TagsTagId200,
  GetPositionsV1Lang200Item,
  GetPositionsV1LangParams,
  GetPositionsV1LangPositionId200,
  GetPricingV1200Item,
  GetPricingV1Id200,
  GetStoreV1200Item,
  GetStoreV1Id200,
  GetTagsV1200Item,
  GetTagsV1Tag200,
  GetTasksV1200Item,
  GetTasksV1Params,
  GetTasksV1TaskId200,
  GetTimezonesV1200Item,
  GetTimezonesV1Timezone200Item,
  GetTimezonesV1TimezoneParams,
  GetUsageV1200Item,
  GetUsageV1Params,
  GetUserV1Uid200,
  GetWorkspacesV1200Item,
  GetWorkspacesV1Params,
  GetWorkspacesV1WorkspaceId200,
  GetWorkspacesV1WorkspaceIdTags200Item,
  PatchCalendarV1CalendarsUserIdCalendarId200,
  PatchCalendarV1CalendarsUserIdCalendarIdBody,
  PatchPinsV1BoardsBoardId200,
  PatchPinsV1BoardsBoardIdBody,
  PatchPinsV1PinsPinId200,
  PatchPinsV1PinsPinIdBody,
  PatchPinsV1TagsTagId200,
  PatchPinsV1TagsTagIdBody,
  PostAuthV1Login200,
  PostAuthV1LoginBody,
  PostAuthV1Logout200,
  PostAuthV1Register200,
  PostAuthV1RegisterBody,
  PostBlogV1Drafts200,
  PostBlogV1DraftsBody,
  PostBlogV1DraftsParams,
  PostBlogV1Posts200,
  PostBlogV1PostsBody,
  PostBlogV1PostsParams,
  PostCalendarV1CalendarsUserId200,
  PostCalendarV1CalendarsUserIdBody,
  PostCalendarV1Events200,
  PostCalendarV1EventsBody,
  PostCalendarV1Schedules200,
  PostCalendarV1SchedulesBody,
  PostCalendarV1Slots200,
  PostCalendarV1SlotsBody,
  PostNewsV1IndexingExtend200,
  PostNotesV1200,
  PostNotesV1Body,
  PostPinsV1BoardsBoardIdAnchorsPinId200,
  PostPinsV1BoardsNew200,
  PostPinsV1BoardsNewBody,
  PostPinsV1PinsNew200,
  PostPinsV1PinsNewBody,
  PostPinsV1PinsPinIdUpload200,
  PostPinsV1PinsPinIdUploadBody,
  PostPinsV1PinsPinIdUploadParams,
  PostPinsV1TagsNew200,
  PostPinsV1TagsNewBody,
  PostTagsV1200,
  PostTagsV1Body,
  PostTasksV1200,
  PostTasksV1Body,
  PostWorkspacesV1200,
  PostWorkspacesV1Body,
  PutCalendarV1SchedulesScheduleId200,
  PutCalendarV1SchedulesScheduleIdBody,
  PutCalendarV1SlotsSlotId200,
  PutCalendarV1SlotsSlotIdBody,
  PutNotesV1NoteId200,
  PutNotesV1NoteIdBody,
  PutTagsV1Tag200,
  PutTagsV1TagBody,
  PutTasksV1TaskId200,
  PutTasksV1TaskIdBody,
  PutWorkspacesV1WorkspaceId200,
  PutWorkspacesV1WorkspaceIdBody
} from '../types';

import { axios } from '../lib/custom-instance';
import type { BodyType } from '../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAuthV1Me = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetAuthV1Me200>(
      {url: `https://api.yz13.ru/auth/v1/me`, method: 'GET'
    },
      options);
    }
  
export const postAuthV1Login = (
    postAuthV1LoginBody: BodyType<PostAuthV1LoginBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostAuthV1Login200>(
      {url: `https://api.yz13.ru/auth/v1/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthV1LoginBody
    },
      options);
    }
  
export const postAuthV1Register = (
    postAuthV1RegisterBody: BodyType<PostAuthV1RegisterBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostAuthV1Register200>(
      {url: `https://api.yz13.ru/auth/v1/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthV1RegisterBody
    },
      options);
    }
  
export const postAuthV1Logout = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostAuthV1Logout200>(
      {url: `https://api.yz13.ru/auth/v1/logout`, method: 'POST'
    },
      options);
    }
  
export const getUsageV1 = (
    params?: GetUsageV1Params,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetUsageV1200Item[]>(
      {url: `https://api.yz13.ru/usage/v1`, method: 'GET',
        params
    },
      options);
    }
  
export const getUserV1Uid = (
    uid: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetUserV1Uid200>(
      {url: `https://api.yz13.ru/user/v1/${uid}`, method: 'GET'
    },
      options);
    }
  
/**
 * Retrieve all available pricing plans
 * @summary Get all pricing plans
 */
export const getPricingV1 = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPricingV1200Item[]>(
      {url: `https://api.yz13.ru/pricing/v1`, method: 'GET'
    },
      options);
    }
  
/**
 * Retrieve a specific pricing plan by its ID
 * @summary Get pricing plan by ID
 */
export const getPricingV1Id = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPricingV1Id200>(
      {url: `https://api.yz13.ru/pricing/v1/${id}`, method: 'GET'
    },
      options);
    }
  
export const getPositionsV1Lang = (
    lang: string,
    params?: GetPositionsV1LangParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPositionsV1Lang200Item[]>(
      {url: `https://api.yz13.ru/positions/v1/${lang}`, method: 'GET',
        params
    },
      options);
    }
  
export const getPositionsV1LangPositionId = (
    lang: string,
    positionId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPositionsV1LangPositionId200>(
      {url: `https://api.yz13.ru/positions/v1/${lang}/${positionId}`, method: 'GET'
    },
      options);
    }
  
export const getWorkspacesV1 = (
    params?: GetWorkspacesV1Params,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetWorkspacesV1200Item[]>(
      {url: `https://api.yz13.ru/workspaces/v1`, method: 'GET',
        params
    },
      options);
    }
  
export const postWorkspacesV1 = (
    postWorkspacesV1Body: BodyType<PostWorkspacesV1Body>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostWorkspacesV1200>(
      {url: `https://api.yz13.ru/workspaces/v1`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postWorkspacesV1Body
    },
      options);
    }
  
export const getWorkspacesV1WorkspaceId = (
    workspaceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetWorkspacesV1WorkspaceId200>(
      {url: `https://api.yz13.ru/workspaces/v1/${workspaceId}`, method: 'GET'
    },
      options);
    }
  
export const putWorkspacesV1WorkspaceId = (
    workspaceId: string,
    putWorkspacesV1WorkspaceIdBody: BodyType<PutWorkspacesV1WorkspaceIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PutWorkspacesV1WorkspaceId200>(
      {url: `https://api.yz13.ru/workspaces/v1/${workspaceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putWorkspacesV1WorkspaceIdBody
    },
      options);
    }
  
export const deleteWorkspacesV1WorkspaceId = (
    workspaceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteWorkspacesV1WorkspaceId200>(
      {url: `https://api.yz13.ru/workspaces/v1/${workspaceId}`, method: 'DELETE'
    },
      options);
    }
  
export const getWorkspacesV1WorkspaceIdTags = (
    workspaceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetWorkspacesV1WorkspaceIdTags200Item[]>(
      {url: `https://api.yz13.ru/workspaces/v1/${workspaceId}/tags`, method: 'GET'
    },
      options);
    }
  
export const getTagsV1 = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetTagsV1200Item[]>(
      {url: `https://api.yz13.ru/tags/v1`, method: 'GET'
    },
      options);
    }
  
export const postTagsV1 = (
    postTagsV1Body: BodyType<PostTagsV1Body>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostTagsV1200>(
      {url: `https://api.yz13.ru/tags/v1`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postTagsV1Body
    },
      options);
    }
  
export const getTagsV1Tag = (
    tag: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetTagsV1Tag200>(
      {url: `https://api.yz13.ru/tags/v1/${tag}`, method: 'GET'
    },
      options);
    }
  
export const putTagsV1Tag = (
    tag: string,
    putTagsV1TagBody: BodyType<PutTagsV1TagBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PutTagsV1Tag200>(
      {url: `https://api.yz13.ru/tags/v1/${tag}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putTagsV1TagBody
    },
      options);
    }
  
export const deleteTagsV1Tag = (
    tag: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteTagsV1Tag200>(
      {url: `https://api.yz13.ru/tags/v1/${tag}`, method: 'DELETE'
    },
      options);
    }
  
export const getTimezonesV1 = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetTimezonesV1200Item[]>(
      {url: `https://api.yz13.ru/timezones/v1`, method: 'GET'
    },
      options);
    }
  
export const getTimezonesV1Timezone = (
    params: GetTimezonesV1TimezoneParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetTimezonesV1Timezone200Item[]>(
      {url: `https://api.yz13.ru/timezones/v1/timezone`, method: 'GET',
        params
    },
      options);
    }
  
export const getNotesV1 = (
    params?: GetNotesV1Params,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetNotesV1200Item[]>(
      {url: `https://api.yz13.ru/notes/v1`, method: 'GET',
        params
    },
      options);
    }
  
export const postNotesV1 = (
    postNotesV1Body: BodyType<PostNotesV1Body>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostNotesV1200>(
      {url: `https://api.yz13.ru/notes/v1`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postNotesV1Body
    },
      options);
    }
  
export const getNotesV1NoteId = (
    noteId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetNotesV1NoteId200>(
      {url: `https://api.yz13.ru/notes/v1/${noteId}`, method: 'GET'
    },
      options);
    }
  
export const putNotesV1NoteId = (
    noteId: string,
    putNotesV1NoteIdBody: BodyType<PutNotesV1NoteIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PutNotesV1NoteId200>(
      {url: `https://api.yz13.ru/notes/v1/${noteId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putNotesV1NoteIdBody
    },
      options);
    }
  
export const deleteNotesV1NoteId = (
    noteId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteNotesV1NoteId200>(
      {url: `https://api.yz13.ru/notes/v1/${noteId}`, method: 'DELETE'
    },
      options);
    }
  
export const postCalendarV1CalendarsUserId = (
    userId: string,
    postCalendarV1CalendarsUserIdBody: BodyType<PostCalendarV1CalendarsUserIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostCalendarV1CalendarsUserId200>(
      {url: `https://api.yz13.ru/calendar/v1/calendars/${userId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postCalendarV1CalendarsUserIdBody
    },
      options);
    }
  
export const getCalendarV1CalendarsUserId = (
    userId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1CalendarsUserId200Item[]>(
      {url: `https://api.yz13.ru/calendar/v1/calendars/${userId}`, method: 'GET'
    },
      options);
    }
  
export const getCalendarV1CalendarsUserIdDefault = (
    userId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1CalendarsUserIdDefault200>(
      {url: `https://api.yz13.ru/calendar/v1/calendars/${userId}/default`, method: 'GET'
    },
      options);
    }
  
export const getCalendarV1CalendarsUserIdCalendarId = (
    userId: string,
    calendarId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1CalendarsUserIdCalendarId200>(
      {url: `https://api.yz13.ru/calendar/v1/calendars/${userId}/${calendarId}`, method: 'GET'
    },
      options);
    }
  
export const patchCalendarV1CalendarsUserIdCalendarId = (
    userId: string,
    calendarId: string,
    patchCalendarV1CalendarsUserIdCalendarIdBody: BodyType<PatchCalendarV1CalendarsUserIdCalendarIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchCalendarV1CalendarsUserIdCalendarId200>(
      {url: `https://api.yz13.ru/calendar/v1/calendars/${userId}/${calendarId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchCalendarV1CalendarsUserIdCalendarIdBody
    },
      options);
    }
  
export const deleteCalendarV1CalendarsUserIdCalendarId = (
    userId: string,
    calendarId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteCalendarV1CalendarsUserIdCalendarId200>(
      {url: `https://api.yz13.ru/calendar/v1/calendars/${userId}/${calendarId}`, method: 'DELETE'
    },
      options);
    }
  
export const getCalendarV1EventsUserId = (
    userId: string,
    params?: GetCalendarV1EventsUserIdParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1EventsUserId200Item[]>(
      {url: `https://api.yz13.ru/calendar/v1/events/${userId}`, method: 'GET',
        params
    },
      options);
    }
  
export const getCalendarV1EventsUserIdType = (
    userId: string,
    type: 'event' | 'appointment',
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1EventsUserIdType200Item[]>(
      {url: `https://api.yz13.ru/calendar/v1/events/${userId}/${type}`, method: 'GET'
    },
      options);
    }
  
export const postCalendarV1Events = (
    postCalendarV1EventsBody: BodyType<PostCalendarV1EventsBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostCalendarV1Events200>(
      {url: `https://api.yz13.ru/calendar/v1/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postCalendarV1EventsBody
    },
      options);
    }
  
export const getCalendarV1SchedulesUserId = (
    userId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1SchedulesUserId200Item[]>(
      {url: `https://api.yz13.ru/calendar/v1/schedules/${userId}`, method: 'GET'
    },
      options);
    }
  
export const getCalendarV1SchedulesUserIdAvailability = (
    userId: string,
    params?: GetCalendarV1SchedulesUserIdAvailabilityParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1SchedulesUserIdAvailability200>(
      {url: `https://api.yz13.ru/calendar/v1/schedules/${userId}/availability`, method: 'GET',
        params
    },
      options);
    }
  
export const postCalendarV1Schedules = (
    postCalendarV1SchedulesBody: BodyType<PostCalendarV1SchedulesBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostCalendarV1Schedules200>(
      {url: `https://api.yz13.ru/calendar/v1/schedules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postCalendarV1SchedulesBody
    },
      options);
    }
  
export const putCalendarV1SchedulesScheduleId = (
    scheduleId: string,
    putCalendarV1SchedulesScheduleIdBody: BodyType<PutCalendarV1SchedulesScheduleIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PutCalendarV1SchedulesScheduleId200>(
      {url: `https://api.yz13.ru/calendar/v1/schedules/${scheduleId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putCalendarV1SchedulesScheduleIdBody
    },
      options);
    }
  
export const deleteCalendarV1SchedulesScheduleId = (
    scheduleId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteCalendarV1SchedulesScheduleId200>(
      {url: `https://api.yz13.ru/calendar/v1/schedules/${scheduleId}`, method: 'DELETE'
    },
      options);
    }
  
export const getCalendarV1Slots = (
    params: GetCalendarV1SlotsParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1Slots200Item[]>(
      {url: `https://api.yz13.ru/calendar/v1/slots`, method: 'GET',
        params
    },
      options);
    }
  
export const postCalendarV1Slots = (
    postCalendarV1SlotsBody: BodyType<PostCalendarV1SlotsBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostCalendarV1Slots200>(
      {url: `https://api.yz13.ru/calendar/v1/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postCalendarV1SlotsBody
    },
      options);
    }
  
export const getCalendarV1SlotsSlotId = (
    slotId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetCalendarV1SlotsSlotId200>(
      {url: `https://api.yz13.ru/calendar/v1/slots/${slotId}`, method: 'GET'
    },
      options);
    }
  
export const putCalendarV1SlotsSlotId = (
    slotId: string,
    putCalendarV1SlotsSlotIdBody: BodyType<PutCalendarV1SlotsSlotIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PutCalendarV1SlotsSlotId200>(
      {url: `https://api.yz13.ru/calendar/v1/slots/${slotId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putCalendarV1SlotsSlotIdBody
    },
      options);
    }
  
export const deleteCalendarV1SlotsSlotId = (
    slotId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteCalendarV1SlotsSlotId200>(
      {url: `https://api.yz13.ru/calendar/v1/slots/${slotId}`, method: 'DELETE'
    },
      options);
    }
  
export const getBlogV1Posts = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetBlogV1Posts200Item[]>(
      {url: `https://api.yz13.ru/blog/v1/posts`, method: 'GET'
    },
      options);
    }
  
export const postBlogV1Posts = (
    postBlogV1PostsBody: BodyType<PostBlogV1PostsBody>,
    params?: PostBlogV1PostsParams,
 options?: SecondParameter<typeof axios>,) => {const formData = new FormData();
formData.append(`file`, postBlogV1PostsBody.file)
if(postBlogV1PostsBody.name !== undefined) {
 formData.append(`name`, postBlogV1PostsBody.name)
 }

      return axios<PostBlogV1Posts200>(
      {url: `https://api.yz13.ru/blog/v1/posts`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }
  
export const getBlogV1Drafts = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetBlogV1Drafts200Item[]>(
      {url: `https://api.yz13.ru/blog/v1/drafts`, method: 'GET'
    },
      options);
    }
  
export const postBlogV1Drafts = (
    postBlogV1DraftsBody: BodyType<PostBlogV1DraftsBody>,
    params?: PostBlogV1DraftsParams,
 options?: SecondParameter<typeof axios>,) => {const formData = new FormData();
formData.append(`file`, postBlogV1DraftsBody.file)
if(postBlogV1DraftsBody.name !== undefined) {
 formData.append(`name`, postBlogV1DraftsBody.name)
 }

      return axios<PostBlogV1Drafts200>(
      {url: `https://api.yz13.ru/blog/v1/drafts`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }
  
export const getTasksV1 = (
    params: GetTasksV1Params,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetTasksV1200Item[]>(
      {url: `https://api.yz13.ru/tasks/v1`, method: 'GET',
        params
    },
      options);
    }
  
export const postTasksV1 = (
    postTasksV1Body: BodyType<PostTasksV1Body>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostTasksV1200>(
      {url: `https://api.yz13.ru/tasks/v1`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postTasksV1Body
    },
      options);
    }
  
export const getTasksV1TaskId = (
    taskId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetTasksV1TaskId200>(
      {url: `https://api.yz13.ru/tasks/v1/${taskId}`, method: 'GET'
    },
      options);
    }
  
export const putTasksV1TaskId = (
    taskId: string,
    putTasksV1TaskIdBody: BodyType<PutTasksV1TaskIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PutTasksV1TaskId200>(
      {url: `https://api.yz13.ru/tasks/v1/${taskId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putTasksV1TaskIdBody
    },
      options);
    }
  
export const deleteTasksV1TaskId = (
    taskId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteTasksV1TaskId200>(
      {url: `https://api.yz13.ru/tasks/v1/${taskId}`, method: 'DELETE'
    },
      options);
    }
  
export const getStoreV1 = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetStoreV1200Item[]>(
      {url: `https://api.yz13.ru/store/v1`, method: 'GET'
    },
      options);
    }
  
export const getStoreV1Id = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetStoreV1Id200>(
      {url: `https://api.yz13.ru/store/v1/${id}`, method: 'GET'
    },
      options);
    }
  
export const postNewsV1Indexing = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string>(
      {url: `https://api.yz13.ru/news/v1/indexing`, method: 'POST'
    },
      options);
    }
  
export const postNewsV1IndexingExtend = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostNewsV1IndexingExtend200>(
      {url: `https://api.yz13.ru/news/v1/indexing/extend`, method: 'POST'
    },
      options);
    }
  
export const getNewsV1 = (
    params?: GetNewsV1Params,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetNewsV1200Item[]>(
      {url: `https://api.yz13.ru/news/v1`, method: 'GET',
        params
    },
      options);
    }
  
export const getNewsV1ContentId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetNewsV1ContentId200>(
      {url: `https://api.yz13.ru/news/v1/content/${id}`, method: 'GET'
    },
      options);
    }
  
export const getNewsV1Search = (
    params: GetNewsV1SearchParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetNewsV1Search200Item[]>(
      {url: `https://api.yz13.ru/news/v1/search`, method: 'GET',
        params
    },
      options);
    }
  
export const getNewsV1Recent = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetNewsV1Recent200Item[]>(
      {url: `https://api.yz13.ru/news/v1/recent`, method: 'GET'
    },
      options);
    }
  
/**
 * Get pins recommendations
 */
export const getPinsV1PinsRecommendations = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1PinsRecommendations200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/recommendations`, method: 'GET'
    },
      options);
    }
  
/**
 * Search pins
 */
export const getPinsV1PinsSearch = (
    params: GetPinsV1PinsSearchParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1PinsSearch200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/search`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get all pins
 */
export const getPinsV1PinsAll = (
    params?: GetPinsV1PinsAllParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1PinsAll200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/all`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get a pin
 */
export const getPinsV1PinsPinId = (
    pinId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1PinsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update a pin
 */
export const patchPinsV1PinsPinId = (
    pinId: string,
    patchPinsV1PinsPinIdBody: BodyType<PatchPinsV1PinsPinIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchPinsV1PinsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchPinsV1PinsPinIdBody
    },
      options);
    }
  
/**
 * Delete a pin
 */
export const deletePinsV1PinsPinId = (
    pinId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeletePinsV1PinsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Get similar pins
 */
export const getPinsV1PinsPinIdSimilar = (
    pinId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1PinsPinIdSimilar200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}/similar`, method: 'GET'
    },
      options);
    }
  
export const getPinsV1PinsPinIdAnchor = (
    pinId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1PinsPinIdAnchor200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}/anchor`, method: 'GET'
    },
      options);
    }
  
/**
 * Upload a file to a pin
 */
export const postPinsV1PinsPinIdUpload = (
    pinId: string,
    postPinsV1PinsPinIdUploadBody: BodyType<PostPinsV1PinsPinIdUploadBody>,
    params: PostPinsV1PinsPinIdUploadParams,
 options?: SecondParameter<typeof axios>,) => {const formData = new FormData();
formData.append(`file`, postPinsV1PinsPinIdUploadBody.file)

      return axios<PostPinsV1PinsPinIdUpload200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }
  
/**
 * Create a pin
 */
export const postPinsV1PinsNew = (
    postPinsV1PinsNewBody: BodyType<PostPinsV1PinsNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostPinsV1PinsNew200>(
      {url: `https://api.yz13.ru/pins/v1/pins/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPinsV1PinsNewBody
    },
      options);
    }
  
/**
 * Get all boards
 */
export const getPinsV1BoardsAll = (
    params?: GetPinsV1BoardsAllParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1BoardsAll200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/boards/all`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get a board
 */
export const getPinsV1BoardsBoardId = (
    boardId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1BoardsBoardId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update a board
 */
export const patchPinsV1BoardsBoardId = (
    boardId: string,
    patchPinsV1BoardsBoardIdBody: BodyType<PatchPinsV1BoardsBoardIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchPinsV1BoardsBoardId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchPinsV1BoardsBoardIdBody
    },
      options);
    }
  
/**
 * Delete a board
 */
export const deletePinsV1BoardsBoardId = (
    boardId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeletePinsV1BoardsBoardId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Get all pins of a board
 */
export const getPinsV1BoardsBoardIdPins = (
    boardId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1BoardsBoardIdPins200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/pins`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a board
 */
export const postPinsV1BoardsNew = (
    postPinsV1BoardsNewBody: BodyType<PostPinsV1BoardsNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostPinsV1BoardsNew200>(
      {url: `https://api.yz13.ru/pins/v1/boards/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPinsV1BoardsNewBody
    },
      options);
    }
  
export const postPinsV1BoardsBoardIdAnchorsPinId = (
    boardId: string,
    pinId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostPinsV1BoardsBoardIdAnchorsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/anchors/${pinId}`, method: 'POST'
    },
      options);
    }
  
export const deletePinsV1BoardsBoardIdAnchorsPinId = (
    boardId: string,
    pinId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeletePinsV1BoardsBoardIdAnchorsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/anchors/${pinId}`, method: 'DELETE'
    },
      options);
    }
  
export const getPinsV1BoardsBoardIdAnchors = (
    boardId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1BoardsBoardIdAnchors200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/anchors`, method: 'GET'
    },
      options);
    }
  
export const getPinsV1TagsSearch = (
    params?: GetPinsV1TagsSearchParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1TagsSearch200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/tags/search`, method: 'GET',
        params
    },
      options);
    }
  
export const getPinsV1TagsAll = (
    params?: GetPinsV1TagsAllParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1TagsAll200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/tags/all`, method: 'GET',
        params
    },
      options);
    }
  
export const getPinsV1TagsTagId = (
    tagId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetPinsV1TagsTagId200>(
      {url: `https://api.yz13.ru/pins/v1/tags/${tagId}`, method: 'GET'
    },
      options);
    }
  
export const patchPinsV1TagsTagId = (
    tagId: string,
    patchPinsV1TagsTagIdBody: BodyType<PatchPinsV1TagsTagIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchPinsV1TagsTagId200>(
      {url: `https://api.yz13.ru/pins/v1/tags/${tagId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchPinsV1TagsTagIdBody
    },
      options);
    }
  
export const deletePinsV1TagsTagId = (
    tagId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeletePinsV1TagsTagId200>(
      {url: `https://api.yz13.ru/pins/v1/tags/${tagId}`, method: 'DELETE'
    },
      options);
    }
  
export const postPinsV1TagsNew = (
    postPinsV1TagsNewBody: BodyType<PostPinsV1TagsNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostPinsV1TagsNew200>(
      {url: `https://api.yz13.ru/pins/v1/tags/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPinsV1TagsNewBody
    },
      options);
    }
  
export const getLinkV1Id = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetLinkV1Id200>(
      {url: `https://api.yz13.ru/link/v1/${id}`, method: 'GET'
    },
      options);
    }
  
export type GetAuthV1MeResult = NonNullable<Awaited<ReturnType<typeof getAuthV1Me>>>
export type PostAuthV1LoginResult = NonNullable<Awaited<ReturnType<typeof postAuthV1Login>>>
export type PostAuthV1RegisterResult = NonNullable<Awaited<ReturnType<typeof postAuthV1Register>>>
export type PostAuthV1LogoutResult = NonNullable<Awaited<ReturnType<typeof postAuthV1Logout>>>
export type GetUsageV1Result = NonNullable<Awaited<ReturnType<typeof getUsageV1>>>
export type GetUserV1UidResult = NonNullable<Awaited<ReturnType<typeof getUserV1Uid>>>
export type GetPricingV1Result = NonNullable<Awaited<ReturnType<typeof getPricingV1>>>
export type GetPricingV1IdResult = NonNullable<Awaited<ReturnType<typeof getPricingV1Id>>>
export type GetPositionsV1LangResult = NonNullable<Awaited<ReturnType<typeof getPositionsV1Lang>>>
export type GetPositionsV1LangPositionIdResult = NonNullable<Awaited<ReturnType<typeof getPositionsV1LangPositionId>>>
export type GetWorkspacesV1Result = NonNullable<Awaited<ReturnType<typeof getWorkspacesV1>>>
export type PostWorkspacesV1Result = NonNullable<Awaited<ReturnType<typeof postWorkspacesV1>>>
export type GetWorkspacesV1WorkspaceIdResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesV1WorkspaceId>>>
export type PutWorkspacesV1WorkspaceIdResult = NonNullable<Awaited<ReturnType<typeof putWorkspacesV1WorkspaceId>>>
export type DeleteWorkspacesV1WorkspaceIdResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspacesV1WorkspaceId>>>
export type GetWorkspacesV1WorkspaceIdTagsResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesV1WorkspaceIdTags>>>
export type GetTagsV1Result = NonNullable<Awaited<ReturnType<typeof getTagsV1>>>
export type PostTagsV1Result = NonNullable<Awaited<ReturnType<typeof postTagsV1>>>
export type GetTagsV1TagResult = NonNullable<Awaited<ReturnType<typeof getTagsV1Tag>>>
export type PutTagsV1TagResult = NonNullable<Awaited<ReturnType<typeof putTagsV1Tag>>>
export type DeleteTagsV1TagResult = NonNullable<Awaited<ReturnType<typeof deleteTagsV1Tag>>>
export type GetTimezonesV1Result = NonNullable<Awaited<ReturnType<typeof getTimezonesV1>>>
export type GetTimezonesV1TimezoneResult = NonNullable<Awaited<ReturnType<typeof getTimezonesV1Timezone>>>
export type GetNotesV1Result = NonNullable<Awaited<ReturnType<typeof getNotesV1>>>
export type PostNotesV1Result = NonNullable<Awaited<ReturnType<typeof postNotesV1>>>
export type GetNotesV1NoteIdResult = NonNullable<Awaited<ReturnType<typeof getNotesV1NoteId>>>
export type PutNotesV1NoteIdResult = NonNullable<Awaited<ReturnType<typeof putNotesV1NoteId>>>
export type DeleteNotesV1NoteIdResult = NonNullable<Awaited<ReturnType<typeof deleteNotesV1NoteId>>>
export type PostCalendarV1CalendarsUserIdResult = NonNullable<Awaited<ReturnType<typeof postCalendarV1CalendarsUserId>>>
export type GetCalendarV1CalendarsUserIdResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1CalendarsUserId>>>
export type GetCalendarV1CalendarsUserIdDefaultResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1CalendarsUserIdDefault>>>
export type GetCalendarV1CalendarsUserIdCalendarIdResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1CalendarsUserIdCalendarId>>>
export type PatchCalendarV1CalendarsUserIdCalendarIdResult = NonNullable<Awaited<ReturnType<typeof patchCalendarV1CalendarsUserIdCalendarId>>>
export type DeleteCalendarV1CalendarsUserIdCalendarIdResult = NonNullable<Awaited<ReturnType<typeof deleteCalendarV1CalendarsUserIdCalendarId>>>
export type GetCalendarV1EventsUserIdResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1EventsUserId>>>
export type GetCalendarV1EventsUserIdTypeResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1EventsUserIdType>>>
export type PostCalendarV1EventsResult = NonNullable<Awaited<ReturnType<typeof postCalendarV1Events>>>
export type GetCalendarV1SchedulesUserIdResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1SchedulesUserId>>>
export type GetCalendarV1SchedulesUserIdAvailabilityResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1SchedulesUserIdAvailability>>>
export type PostCalendarV1SchedulesResult = NonNullable<Awaited<ReturnType<typeof postCalendarV1Schedules>>>
export type PutCalendarV1SchedulesScheduleIdResult = NonNullable<Awaited<ReturnType<typeof putCalendarV1SchedulesScheduleId>>>
export type DeleteCalendarV1SchedulesScheduleIdResult = NonNullable<Awaited<ReturnType<typeof deleteCalendarV1SchedulesScheduleId>>>
export type GetCalendarV1SlotsResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1Slots>>>
export type PostCalendarV1SlotsResult = NonNullable<Awaited<ReturnType<typeof postCalendarV1Slots>>>
export type GetCalendarV1SlotsSlotIdResult = NonNullable<Awaited<ReturnType<typeof getCalendarV1SlotsSlotId>>>
export type PutCalendarV1SlotsSlotIdResult = NonNullable<Awaited<ReturnType<typeof putCalendarV1SlotsSlotId>>>
export type DeleteCalendarV1SlotsSlotIdResult = NonNullable<Awaited<ReturnType<typeof deleteCalendarV1SlotsSlotId>>>
export type GetBlogV1PostsResult = NonNullable<Awaited<ReturnType<typeof getBlogV1Posts>>>
export type PostBlogV1PostsResult = NonNullable<Awaited<ReturnType<typeof postBlogV1Posts>>>
export type GetBlogV1DraftsResult = NonNullable<Awaited<ReturnType<typeof getBlogV1Drafts>>>
export type PostBlogV1DraftsResult = NonNullable<Awaited<ReturnType<typeof postBlogV1Drafts>>>
export type GetTasksV1Result = NonNullable<Awaited<ReturnType<typeof getTasksV1>>>
export type PostTasksV1Result = NonNullable<Awaited<ReturnType<typeof postTasksV1>>>
export type GetTasksV1TaskIdResult = NonNullable<Awaited<ReturnType<typeof getTasksV1TaskId>>>
export type PutTasksV1TaskIdResult = NonNullable<Awaited<ReturnType<typeof putTasksV1TaskId>>>
export type DeleteTasksV1TaskIdResult = NonNullable<Awaited<ReturnType<typeof deleteTasksV1TaskId>>>
export type GetStoreV1Result = NonNullable<Awaited<ReturnType<typeof getStoreV1>>>
export type GetStoreV1IdResult = NonNullable<Awaited<ReturnType<typeof getStoreV1Id>>>
export type PostNewsV1IndexingResult = NonNullable<Awaited<ReturnType<typeof postNewsV1Indexing>>>
export type PostNewsV1IndexingExtendResult = NonNullable<Awaited<ReturnType<typeof postNewsV1IndexingExtend>>>
export type GetNewsV1Result = NonNullable<Awaited<ReturnType<typeof getNewsV1>>>
export type GetNewsV1ContentIdResult = NonNullable<Awaited<ReturnType<typeof getNewsV1ContentId>>>
export type GetNewsV1SearchResult = NonNullable<Awaited<ReturnType<typeof getNewsV1Search>>>
export type GetNewsV1RecentResult = NonNullable<Awaited<ReturnType<typeof getNewsV1Recent>>>
export type GetPinsV1PinsRecommendationsResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsRecommendations>>>
export type GetPinsV1PinsSearchResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsSearch>>>
export type GetPinsV1PinsAllResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsAll>>>
export type GetPinsV1PinsPinIdResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsPinId>>>
export type PatchPinsV1PinsPinIdResult = NonNullable<Awaited<ReturnType<typeof patchPinsV1PinsPinId>>>
export type DeletePinsV1PinsPinIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1PinsPinId>>>
export type GetPinsV1PinsPinIdSimilarResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsPinIdSimilar>>>
export type GetPinsV1PinsPinIdAnchorResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsPinIdAnchor>>>
export type PostPinsV1PinsPinIdUploadResult = NonNullable<Awaited<ReturnType<typeof postPinsV1PinsPinIdUpload>>>
export type PostPinsV1PinsNewResult = NonNullable<Awaited<ReturnType<typeof postPinsV1PinsNew>>>
export type GetPinsV1BoardsAllResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsAll>>>
export type GetPinsV1BoardsBoardIdResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsBoardId>>>
export type PatchPinsV1BoardsBoardIdResult = NonNullable<Awaited<ReturnType<typeof patchPinsV1BoardsBoardId>>>
export type DeletePinsV1BoardsBoardIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1BoardsBoardId>>>
export type GetPinsV1BoardsBoardIdPinsResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsBoardIdPins>>>
export type PostPinsV1BoardsNewResult = NonNullable<Awaited<ReturnType<typeof postPinsV1BoardsNew>>>
export type PostPinsV1BoardsBoardIdAnchorsPinIdResult = NonNullable<Awaited<ReturnType<typeof postPinsV1BoardsBoardIdAnchorsPinId>>>
export type DeletePinsV1BoardsBoardIdAnchorsPinIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1BoardsBoardIdAnchorsPinId>>>
export type GetPinsV1BoardsBoardIdAnchorsResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsBoardIdAnchors>>>
export type GetPinsV1TagsSearchResult = NonNullable<Awaited<ReturnType<typeof getPinsV1TagsSearch>>>
export type GetPinsV1TagsAllResult = NonNullable<Awaited<ReturnType<typeof getPinsV1TagsAll>>>
export type GetPinsV1TagsTagIdResult = NonNullable<Awaited<ReturnType<typeof getPinsV1TagsTagId>>>
export type PatchPinsV1TagsTagIdResult = NonNullable<Awaited<ReturnType<typeof patchPinsV1TagsTagId>>>
export type DeletePinsV1TagsTagIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1TagsTagId>>>
export type PostPinsV1TagsNewResult = NonNullable<Awaited<ReturnType<typeof postPinsV1TagsNew>>>
export type GetLinkV1IdResult = NonNullable<Awaited<ReturnType<typeof getLinkV1Id>>>
