/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type {
  DeletePinsV1BoardsBoardId200,
  DeletePinsV1BoardsBoardIdAnchorsPinId200,
  DeletePinsV1PinsPinId200,
  DeletePinsV1TagsTagId200,
  GetAuthV1Me200,
  GetBlogV1Drafts200Item,
  GetBlogV1Posts200Item,
  GetPinsV1BoardsAll200Item,
  GetPinsV1BoardsAllParams,
  GetPinsV1BoardsBoardId200,
  GetPinsV1BoardsBoardIdAnchors200Item,
  GetPinsV1BoardsBoardIdPins200Item,
  GetPinsV1PinsAll200Item,
  GetPinsV1PinsAllParams,
  GetPinsV1PinsPinId200,
  GetPinsV1PinsPinIdAnchor200,
  GetPinsV1PinsPinIdSimilar200Item,
  GetPinsV1PinsRecommendations200Item,
  GetPinsV1PinsSearch200Item,
  GetPinsV1PinsSearchParams,
  GetPinsV1TagsAll200Item,
  GetPinsV1TagsAllParams,
  GetPinsV1TagsSearch200Item,
  GetPinsV1TagsSearchParams,
  GetPinsV1TagsTagId200,
  GetUsersV1Uid200,
  PatchPinsV1BoardsBoardId200,
  PatchPinsV1BoardsBoardIdBody,
  PatchPinsV1PinsPinId200,
  PatchPinsV1PinsPinIdBody,
  PatchPinsV1TagsTagId200,
  PatchPinsV1TagsTagIdBody,
  PostAuthV1Login200,
  PostAuthV1LoginBody,
  PostAuthV1Logout200,
  PostAuthV1Register200,
  PostAuthV1RegisterBody,
  PostBlogV1Drafts200,
  PostBlogV1DraftsBody,
  PostBlogV1DraftsParams,
  PostBlogV1Posts200,
  PostBlogV1PostsBody,
  PostBlogV1PostsParams,
  PostClicksV1Track200,
  PostPinsV1BoardsBoardIdAnchorsPinId200,
  PostPinsV1BoardsNew200,
  PostPinsV1BoardsNewBody,
  PostPinsV1PinsNew200,
  PostPinsV1PinsNewBody,
  PostPinsV1PinsPinIdUpload200,
  PostPinsV1PinsPinIdUploadBody,
  PostPinsV1PinsPinIdUploadParams,
  PostPinsV1TagsNew200,
  PostPinsV1TagsNewBody
} from '../types';

import { axios } from '../lib/custom-instance';
import type { BodyType } from '../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUsersV1Uid = (
    uid: string,
 options?: SecondParameter<typeof axios<GetUsersV1Uid200>>,) => {
      return axios<GetUsersV1Uid200>(
      {url: `https://api.yz13.ru/users/v1/${uid}`, method: 'GET'
    },
      options);
    }
  
export const getAuthV1Me = (
    
 options?: SecondParameter<typeof axios<GetAuthV1Me200>>,) => {
      return axios<GetAuthV1Me200>(
      {url: `https://api.yz13.ru/auth/v1/me`, method: 'GET'
    },
      options);
    }
  
export const postAuthV1Login = (
    postAuthV1LoginBody: BodyType<PostAuthV1LoginBody>,
 options?: SecondParameter<typeof axios<PostAuthV1Login200>>,) => {
      return axios<PostAuthV1Login200>(
      {url: `https://api.yz13.ru/auth/v1/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthV1LoginBody
    },
      options);
    }
  
export const postAuthV1Register = (
    postAuthV1RegisterBody: BodyType<PostAuthV1RegisterBody>,
 options?: SecondParameter<typeof axios<PostAuthV1Register200>>,) => {
      return axios<PostAuthV1Register200>(
      {url: `https://api.yz13.ru/auth/v1/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthV1RegisterBody
    },
      options);
    }
  
export const postAuthV1Logout = (
    
 options?: SecondParameter<typeof axios<PostAuthV1Logout200>>,) => {
      return axios<PostAuthV1Logout200>(
      {url: `https://api.yz13.ru/auth/v1/logout`, method: 'POST'
    },
      options);
    }
  
export const getBlogV1Posts = (
    
 options?: SecondParameter<typeof axios<GetBlogV1Posts200Item[]>>,) => {
      return axios<GetBlogV1Posts200Item[]>(
      {url: `https://api.yz13.ru/blog/v1/posts`, method: 'GET'
    },
      options);
    }
  
export const postBlogV1Posts = (
    postBlogV1PostsBody: BodyType<PostBlogV1PostsBody>,
    params?: PostBlogV1PostsParams,
 options?: SecondParameter<typeof axios<PostBlogV1Posts200>>,) => {const formData = new FormData();
formData.append(`file`, postBlogV1PostsBody.file)
if(postBlogV1PostsBody.name !== undefined) {
 formData.append(`name`, postBlogV1PostsBody.name)
 }

      return axios<PostBlogV1Posts200>(
      {url: `https://api.yz13.ru/blog/v1/posts`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }
  
export const getBlogV1Drafts = (
    
 options?: SecondParameter<typeof axios<GetBlogV1Drafts200Item[]>>,) => {
      return axios<GetBlogV1Drafts200Item[]>(
      {url: `https://api.yz13.ru/blog/v1/drafts`, method: 'GET'
    },
      options);
    }
  
export const postBlogV1Drafts = (
    postBlogV1DraftsBody: BodyType<PostBlogV1DraftsBody>,
    params?: PostBlogV1DraftsParams,
 options?: SecondParameter<typeof axios<PostBlogV1Drafts200>>,) => {const formData = new FormData();
formData.append(`file`, postBlogV1DraftsBody.file)
if(postBlogV1DraftsBody.name !== undefined) {
 formData.append(`name`, postBlogV1DraftsBody.name)
 }

      return axios<PostBlogV1Drafts200>(
      {url: `https://api.yz13.ru/blog/v1/drafts`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }
  
/**
 * Get pins recommendations
 */
export const getPinsV1PinsRecommendations = (
    
 options?: SecondParameter<typeof axios<GetPinsV1PinsRecommendations200Item[]>>,) => {
      return axios<GetPinsV1PinsRecommendations200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/recommendations`, method: 'GET'
    },
      options);
    }
  
/**
 * Search pins
 */
export const getPinsV1PinsSearch = (
    params: GetPinsV1PinsSearchParams,
 options?: SecondParameter<typeof axios<GetPinsV1PinsSearch200Item[]>>,) => {
      return axios<GetPinsV1PinsSearch200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/search`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get all pins
 */
export const getPinsV1PinsAll = (
    params?: GetPinsV1PinsAllParams,
 options?: SecondParameter<typeof axios<GetPinsV1PinsAll200Item[]>>,) => {
      return axios<GetPinsV1PinsAll200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/all`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get a pin
 */
export const getPinsV1PinsPinId = (
    pinId: string,
 options?: SecondParameter<typeof axios<GetPinsV1PinsPinId200>>,) => {
      return axios<GetPinsV1PinsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update a pin
 */
export const patchPinsV1PinsPinId = (
    pinId: string,
    patchPinsV1PinsPinIdBody: BodyType<PatchPinsV1PinsPinIdBody>,
 options?: SecondParameter<typeof axios<PatchPinsV1PinsPinId200>>,) => {
      return axios<PatchPinsV1PinsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchPinsV1PinsPinIdBody
    },
      options);
    }
  
/**
 * Delete a pin
 */
export const deletePinsV1PinsPinId = (
    pinId: string,
 options?: SecondParameter<typeof axios<DeletePinsV1PinsPinId200>>,) => {
      return axios<DeletePinsV1PinsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Get similar pins
 */
export const getPinsV1PinsPinIdSimilar = (
    pinId: string,
 options?: SecondParameter<typeof axios<GetPinsV1PinsPinIdSimilar200Item[]>>,) => {
      return axios<GetPinsV1PinsPinIdSimilar200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}/similar`, method: 'GET'
    },
      options);
    }
  
export const getPinsV1PinsPinIdAnchor = (
    pinId: string,
 options?: SecondParameter<typeof axios<GetPinsV1PinsPinIdAnchor200>>,) => {
      return axios<GetPinsV1PinsPinIdAnchor200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}/anchor`, method: 'GET'
    },
      options);
    }
  
/**
 * Upload a file to a pin
 */
export const postPinsV1PinsPinIdUpload = (
    pinId: string,
    postPinsV1PinsPinIdUploadBody: BodyType<PostPinsV1PinsPinIdUploadBody>,
    params: PostPinsV1PinsPinIdUploadParams,
 options?: SecondParameter<typeof axios<PostPinsV1PinsPinIdUpload200>>,) => {const formData = new FormData();
formData.append(`file`, postPinsV1PinsPinIdUploadBody.file)

      return axios<PostPinsV1PinsPinIdUpload200>(
      {url: `https://api.yz13.ru/pins/v1/pins/${pinId}/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params
    },
      options);
    }
  
/**
 * Create a pin
 */
export const postPinsV1PinsNew = (
    postPinsV1PinsNewBody: BodyType<PostPinsV1PinsNewBody>,
 options?: SecondParameter<typeof axios<PostPinsV1PinsNew200>>,) => {
      return axios<PostPinsV1PinsNew200>(
      {url: `https://api.yz13.ru/pins/v1/pins/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPinsV1PinsNewBody
    },
      options);
    }
  
/**
 * Get all boards
 */
export const getPinsV1BoardsAll = (
    params?: GetPinsV1BoardsAllParams,
 options?: SecondParameter<typeof axios<GetPinsV1BoardsAll200Item[]>>,) => {
      return axios<GetPinsV1BoardsAll200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/boards/all`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get a board
 */
export const getPinsV1BoardsBoardId = (
    boardId: string,
 options?: SecondParameter<typeof axios<GetPinsV1BoardsBoardId200>>,) => {
      return axios<GetPinsV1BoardsBoardId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update a board
 */
export const patchPinsV1BoardsBoardId = (
    boardId: string,
    patchPinsV1BoardsBoardIdBody: BodyType<PatchPinsV1BoardsBoardIdBody>,
 options?: SecondParameter<typeof axios<PatchPinsV1BoardsBoardId200>>,) => {
      return axios<PatchPinsV1BoardsBoardId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchPinsV1BoardsBoardIdBody
    },
      options);
    }
  
/**
 * Delete a board
 */
export const deletePinsV1BoardsBoardId = (
    boardId: string,
 options?: SecondParameter<typeof axios<DeletePinsV1BoardsBoardId200>>,) => {
      return axios<DeletePinsV1BoardsBoardId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Get all pins of a board
 */
export const getPinsV1BoardsBoardIdPins = (
    boardId: string,
 options?: SecondParameter<typeof axios<GetPinsV1BoardsBoardIdPins200Item[]>>,) => {
      return axios<GetPinsV1BoardsBoardIdPins200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/pins`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a board
 */
export const postPinsV1BoardsNew = (
    postPinsV1BoardsNewBody: BodyType<PostPinsV1BoardsNewBody>,
 options?: SecondParameter<typeof axios<PostPinsV1BoardsNew200>>,) => {
      return axios<PostPinsV1BoardsNew200>(
      {url: `https://api.yz13.ru/pins/v1/boards/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPinsV1BoardsNewBody
    },
      options);
    }
  
export const postPinsV1BoardsBoardIdAnchorsPinId = (
    boardId: string,
    pinId: string,
 options?: SecondParameter<typeof axios<PostPinsV1BoardsBoardIdAnchorsPinId200>>,) => {
      return axios<PostPinsV1BoardsBoardIdAnchorsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/anchors/${pinId}`, method: 'POST'
    },
      options);
    }
  
export const deletePinsV1BoardsBoardIdAnchorsPinId = (
    boardId: string,
    pinId: string,
 options?: SecondParameter<typeof axios<DeletePinsV1BoardsBoardIdAnchorsPinId200>>,) => {
      return axios<DeletePinsV1BoardsBoardIdAnchorsPinId200>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/anchors/${pinId}`, method: 'DELETE'
    },
      options);
    }
  
export const getPinsV1BoardsBoardIdAnchors = (
    boardId: string,
 options?: SecondParameter<typeof axios<GetPinsV1BoardsBoardIdAnchors200Item[]>>,) => {
      return axios<GetPinsV1BoardsBoardIdAnchors200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/boards/${boardId}/anchors`, method: 'GET'
    },
      options);
    }
  
export const getPinsV1TagsSearch = (
    params?: GetPinsV1TagsSearchParams,
 options?: SecondParameter<typeof axios<GetPinsV1TagsSearch200Item[]>>,) => {
      return axios<GetPinsV1TagsSearch200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/tags/search`, method: 'GET',
        params
    },
      options);
    }
  
export const getPinsV1TagsAll = (
    params?: GetPinsV1TagsAllParams,
 options?: SecondParameter<typeof axios<GetPinsV1TagsAll200Item[]>>,) => {
      return axios<GetPinsV1TagsAll200Item[]>(
      {url: `https://api.yz13.ru/pins/v1/tags/all`, method: 'GET',
        params
    },
      options);
    }
  
export const getPinsV1TagsTagId = (
    tagId: string,
 options?: SecondParameter<typeof axios<GetPinsV1TagsTagId200>>,) => {
      return axios<GetPinsV1TagsTagId200>(
      {url: `https://api.yz13.ru/pins/v1/tags/${tagId}`, method: 'GET'
    },
      options);
    }
  
export const patchPinsV1TagsTagId = (
    tagId: string,
    patchPinsV1TagsTagIdBody: BodyType<PatchPinsV1TagsTagIdBody>,
 options?: SecondParameter<typeof axios<PatchPinsV1TagsTagId200>>,) => {
      return axios<PatchPinsV1TagsTagId200>(
      {url: `https://api.yz13.ru/pins/v1/tags/${tagId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchPinsV1TagsTagIdBody
    },
      options);
    }
  
export const deletePinsV1TagsTagId = (
    tagId: string,
 options?: SecondParameter<typeof axios<DeletePinsV1TagsTagId200>>,) => {
      return axios<DeletePinsV1TagsTagId200>(
      {url: `https://api.yz13.ru/pins/v1/tags/${tagId}`, method: 'DELETE'
    },
      options);
    }
  
export const postPinsV1TagsNew = (
    postPinsV1TagsNewBody: BodyType<PostPinsV1TagsNewBody>,
 options?: SecondParameter<typeof axios<PostPinsV1TagsNew200>>,) => {
      return axios<PostPinsV1TagsNew200>(
      {url: `https://api.yz13.ru/pins/v1/tags/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPinsV1TagsNewBody
    },
      options);
    }
  
export const postClicksV1Track = (
    
 options?: SecondParameter<typeof axios<PostClicksV1Track200>>,) => {
      return axios<PostClicksV1Track200>(
      {url: `https://api.yz13.ru/clicks/v1/track`, method: 'POST'
    },
      options);
    }
  
export type GetUsersV1UidResult = NonNullable<Awaited<ReturnType<typeof getUsersV1Uid>>>
export type GetAuthV1MeResult = NonNullable<Awaited<ReturnType<typeof getAuthV1Me>>>
export type PostAuthV1LoginResult = NonNullable<Awaited<ReturnType<typeof postAuthV1Login>>>
export type PostAuthV1RegisterResult = NonNullable<Awaited<ReturnType<typeof postAuthV1Register>>>
export type PostAuthV1LogoutResult = NonNullable<Awaited<ReturnType<typeof postAuthV1Logout>>>
export type GetBlogV1PostsResult = NonNullable<Awaited<ReturnType<typeof getBlogV1Posts>>>
export type PostBlogV1PostsResult = NonNullable<Awaited<ReturnType<typeof postBlogV1Posts>>>
export type GetBlogV1DraftsResult = NonNullable<Awaited<ReturnType<typeof getBlogV1Drafts>>>
export type PostBlogV1DraftsResult = NonNullable<Awaited<ReturnType<typeof postBlogV1Drafts>>>
export type GetPinsV1PinsRecommendationsResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsRecommendations>>>
export type GetPinsV1PinsSearchResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsSearch>>>
export type GetPinsV1PinsAllResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsAll>>>
export type GetPinsV1PinsPinIdResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsPinId>>>
export type PatchPinsV1PinsPinIdResult = NonNullable<Awaited<ReturnType<typeof patchPinsV1PinsPinId>>>
export type DeletePinsV1PinsPinIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1PinsPinId>>>
export type GetPinsV1PinsPinIdSimilarResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsPinIdSimilar>>>
export type GetPinsV1PinsPinIdAnchorResult = NonNullable<Awaited<ReturnType<typeof getPinsV1PinsPinIdAnchor>>>
export type PostPinsV1PinsPinIdUploadResult = NonNullable<Awaited<ReturnType<typeof postPinsV1PinsPinIdUpload>>>
export type PostPinsV1PinsNewResult = NonNullable<Awaited<ReturnType<typeof postPinsV1PinsNew>>>
export type GetPinsV1BoardsAllResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsAll>>>
export type GetPinsV1BoardsBoardIdResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsBoardId>>>
export type PatchPinsV1BoardsBoardIdResult = NonNullable<Awaited<ReturnType<typeof patchPinsV1BoardsBoardId>>>
export type DeletePinsV1BoardsBoardIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1BoardsBoardId>>>
export type GetPinsV1BoardsBoardIdPinsResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsBoardIdPins>>>
export type PostPinsV1BoardsNewResult = NonNullable<Awaited<ReturnType<typeof postPinsV1BoardsNew>>>
export type PostPinsV1BoardsBoardIdAnchorsPinIdResult = NonNullable<Awaited<ReturnType<typeof postPinsV1BoardsBoardIdAnchorsPinId>>>
export type DeletePinsV1BoardsBoardIdAnchorsPinIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1BoardsBoardIdAnchorsPinId>>>
export type GetPinsV1BoardsBoardIdAnchorsResult = NonNullable<Awaited<ReturnType<typeof getPinsV1BoardsBoardIdAnchors>>>
export type GetPinsV1TagsSearchResult = NonNullable<Awaited<ReturnType<typeof getPinsV1TagsSearch>>>
export type GetPinsV1TagsAllResult = NonNullable<Awaited<ReturnType<typeof getPinsV1TagsAll>>>
export type GetPinsV1TagsTagIdResult = NonNullable<Awaited<ReturnType<typeof getPinsV1TagsTagId>>>
export type PatchPinsV1TagsTagIdResult = NonNullable<Awaited<ReturnType<typeof patchPinsV1TagsTagId>>>
export type DeletePinsV1TagsTagIdResult = NonNullable<Awaited<ReturnType<typeof deletePinsV1TagsTagId>>>
export type PostPinsV1TagsNewResult = NonNullable<Awaited<ReturnType<typeof postPinsV1TagsNew>>>
export type PostClicksV1TrackResult = NonNullable<Awaited<ReturnType<typeof postClicksV1Track>>>
