/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteV1CalendarId200,
  DeleteV1EventsId200,
  GetV1AuthCurrent200,
  GetV1AuthCurrentSession200,
  GetV1CalendarId200,
  GetV1CalendarUserUid200Item,
  GetV1CalendarUserUidDefault200,
  GetV1ChartsNews200Item,
  GetV1EventsId200,
  GetV1EventsUserUid200Item,
  GetV1EventsUserUidParams,
  GetV1NewsArticleArticleId200,
  GetV1NewsArticles200Item,
  GetV1NewsArticlesParams,
  GetV1NewsArticlesSourceId200Item,
  GetV1NewsCountryCodeArticles200Item,
  GetV1NewsCountryCodeArticlesParams,
  GetV1NewsCountryCodeSources200Item,
  GetV1NewsNewsSources200Item,
  GetV1NewsNewsSourcesParams,
  GetV1NewsNewsSourcesSourceId200,
  GetV1PositionsLang200Item,
  GetV1PositionsLangPositionId200,
  GetV1Pricing200Item,
  GetV1PricingShort200Item,
  GetV1RoomsId200,
  GetV1ScheduleUid200,
  GetV1ScheduleUidAvailable200,
  GetV1ScheduleUidAvailableParams,
  GetV1Store200Item,
  GetV1StoreId200,
  GetV1UserUid200,
  PatchV1CalendarId200,
  PatchV1CalendarIdBody,
  PatchV1EventsId200,
  PatchV1EventsIdBody,
  PatchV1NewsRepatch200,
  PatchV1UserUid200,
  PatchV1UserUidBody,
  PostV1AuthLogin200,
  PostV1AuthLoginBody,
  PostV1AuthLogout200,
  PostV1AuthSignup200,
  PostV1AuthSignupBody,
  PostV1CalendarUserUid200,
  PostV1CalendarUserUidBody,
  PostV1Events200,
  PostV1EventsBody,
  PostV1NewsArticlesNew200,
  PostV1NewsArticlesNewBody,
  PostV1RoomsNew200,
  PostV1RoomsNewBody,
  PostV1Store200,
  PostV1StoreBody
} from '../types';

import { axios } from '../lib/custom-instance';
import type { BodyType } from '../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getV1PositionsLang = (
    lang: 'en' | 'ru',
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1PositionsLang200Item[]>(
      {url: `https://api.yz13.ru/v1/positions/${lang}`, method: 'GET'
    },
      options);
    }
  
export const getV1PositionsLangPositionId = (
    lang: 'en' | 'ru',
    positionId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1PositionsLangPositionId200>(
      {url: `https://api.yz13.ru/v1/positions/${lang}/${positionId}`, method: 'GET'
    },
      options);
    }
  
export const getV1Pricing = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1Pricing200Item[]>(
      {url: `https://api.yz13.ru/v1/pricing`, method: 'GET'
    },
      options);
    }
  
export const getV1PricingShort = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1PricingShort200Item[]>(
      {url: `https://api.yz13.ru/v1/pricing/short`, method: 'GET'
    },
      options);
    }
  
export const getV1UserUid = (
    uid: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1UserUid200>(
      {url: `https://api.yz13.ru/v1/user/${uid}`, method: 'GET'
    },
      options);
    }
  
export const patchV1UserUid = (
    uid: string,
    patchV1UserUidBody: BodyType<PatchV1UserUidBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchV1UserUid200>(
      {url: `https://api.yz13.ru/v1/user/${uid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchV1UserUidBody
    },
      options);
    }
  
export const getV1AuthCurrent = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1AuthCurrent200>(
      {url: `https://api.yz13.ru/v1/auth/current`, method: 'GET'
    },
      options);
    }
  
export const getV1AuthCurrentSession = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1AuthCurrentSession200>(
      {url: `https://api.yz13.ru/v1/auth/current/session`, method: 'GET'
    },
      options);
    }
  
export const postV1AuthLogin = (
    postV1AuthLoginBody: BodyType<PostV1AuthLoginBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1AuthLogin200>(
      {url: `https://api.yz13.ru/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1AuthLoginBody
    },
      options);
    }
  
export const postV1AuthSignup = (
    postV1AuthSignupBody: BodyType<PostV1AuthSignupBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1AuthSignup200>(
      {url: `https://api.yz13.ru/v1/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1AuthSignupBody
    },
      options);
    }
  
export const postV1AuthLogout = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1AuthLogout200>(
      {url: `https://api.yz13.ru/v1/auth/logout`, method: 'POST'
    },
      options);
    }
  
export const getV1RoomsId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1RoomsId200>(
      {url: `https://api.yz13.ru/v1/rooms/${id}`, method: 'GET'
    },
      options);
    }
  
export const postV1RoomsNew = (
    postV1RoomsNewBody: BodyType<PostV1RoomsNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1RoomsNew200>(
      {url: `https://api.yz13.ru/v1/rooms/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1RoomsNewBody
    },
      options);
    }
  
export const getV1NewsNewsSources = (
    params?: GetV1NewsNewsSourcesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsNewsSources200Item[]>(
      {url: `https://api.yz13.ru/v1/news/news-sources`, method: 'GET',
        params
    },
      options);
    }
  
export const getV1NewsNewsSourcesSourceId = (
    sourceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsNewsSourcesSourceId200>(
      {url: `https://api.yz13.ru/v1/news/news-sources/${sourceId}`, method: 'GET'
    },
      options);
    }
  
export const getV1NewsCountryCodeSources = (
    code: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsCountryCodeSources200Item[]>(
      {url: `https://api.yz13.ru/v1/news/country/${code}/sources`, method: 'GET'
    },
      options);
    }
  
export const getV1NewsArticles = (
    params?: GetV1NewsArticlesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsArticles200Item[]>(
      {url: `https://api.yz13.ru/v1/news/articles`, method: 'GET',
        params
    },
      options);
    }
  
export const getV1NewsArticlesSourceId = (
    sourceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsArticlesSourceId200Item[]>(
      {url: `https://api.yz13.ru/v1/news/articles/${sourceId}`, method: 'GET'
    },
      options);
    }
  
export const postV1NewsArticlesNew = (
    postV1NewsArticlesNewBody: BodyType<PostV1NewsArticlesNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1NewsArticlesNew200>(
      {url: `https://api.yz13.ru/v1/news/articles/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1NewsArticlesNewBody
    },
      options);
    }
  
export const getV1NewsCountryCodeArticles = (
    code: string,
    params?: GetV1NewsCountryCodeArticlesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsCountryCodeArticles200Item[]>(
      {url: `https://api.yz13.ru/v1/news/country/${code}/articles`, method: 'GET',
        params
    },
      options);
    }
  
export const getV1NewsArticleArticleId = (
    articleId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsArticleArticleId200>(
      {url: `https://api.yz13.ru/v1/news/article/${articleId}`, method: 'GET'
    },
      options);
    }
  
export const getV1NewsCodes = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string[]>(
      {url: `https://api.yz13.ru/v1/news/codes`, method: 'GET'
    },
      options);
    }
  
export const getV1NewsCategories = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string[]>(
      {url: `https://api.yz13.ru/v1/news/categories`, method: 'GET'
    },
      options);
    }
  
export const patchV1NewsRepatch = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchV1NewsRepatch200>(
      {url: `https://api.yz13.ru/v1/news/repatch`, method: 'PATCH'
    },
      options);
    }
  
export const postV1NewsCacheClear = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string>(
      {url: `https://api.yz13.ru/v1/news/cache/clear`, method: 'POST'
    },
      options);
    }
  
export const postV1Events = (
    postV1EventsBody: BodyType<PostV1EventsBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1Events200>(
      {url: `https://api.yz13.ru/v1/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1EventsBody
    },
      options);
    }
  
export const getV1EventsUserUid = (
    uid: string,
    params?: GetV1EventsUserUidParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1EventsUserUid200Item[]>(
      {url: `https://api.yz13.ru/v1/events/user/${uid}`, method: 'GET',
        params
    },
      options);
    }
  
export const getV1EventsId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1EventsId200>(
      {url: `https://api.yz13.ru/v1/events/${id}`, method: 'GET'
    },
      options);
    }
  
export const patchV1EventsId = (
    id: string,
    patchV1EventsIdBody: BodyType<PatchV1EventsIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchV1EventsId200>(
      {url: `https://api.yz13.ru/v1/events/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchV1EventsIdBody
    },
      options);
    }
  
export const deleteV1EventsId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteV1EventsId200>(
      {url: `https://api.yz13.ru/v1/events/${id}`, method: 'DELETE'
    },
      options);
    }
  
export const getV1Store = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1Store200Item[]>(
      {url: `https://api.yz13.ru/v1/store`, method: 'GET'
    },
      options);
    }
  
export const postV1Store = (
    postV1StoreBody: BodyType<PostV1StoreBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1Store200>(
      {url: `https://api.yz13.ru/v1/store`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1StoreBody
    },
      options);
    }
  
export const getV1StoreId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1StoreId200>(
      {url: `https://api.yz13.ru/v1/store/${id}`, method: 'GET'
    },
      options);
    }
  
export const getV1ScheduleUid = (
    uid: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1ScheduleUid200>(
      {url: `https://api.yz13.ru/v1/schedule/${uid}`, method: 'GET'
    },
      options);
    }
  
export const getV1ScheduleUidAvailable = (
    uid: string,
    params?: GetV1ScheduleUidAvailableParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1ScheduleUidAvailable200>(
      {url: `https://api.yz13.ru/v1/schedule/${uid}/available`, method: 'GET',
        params
    },
      options);
    }
  
export const getV1ChartsNews = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1ChartsNews200Item[]>(
      {url: `https://api.yz13.ru/v1/charts/news`, method: 'GET'
    },
      options);
    }
  
export const getV1CalendarUserUidDefault = (
    uid: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1CalendarUserUidDefault200>(
      {url: `https://api.yz13.ru/v1/calendar/user/${uid}/default`, method: 'GET'
    },
      options);
    }
  
export const getV1CalendarUserUid = (
    uid: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1CalendarUserUid200Item[]>(
      {url: `https://api.yz13.ru/v1/calendar/user/${uid}`, method: 'GET'
    },
      options);
    }
  
export const postV1CalendarUserUid = (
    uid: string,
    postV1CalendarUserUidBody: BodyType<PostV1CalendarUserUidBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1CalendarUserUid200>(
      {url: `https://api.yz13.ru/v1/calendar/user/${uid}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1CalendarUserUidBody
    },
      options);
    }
  
export const getV1CalendarId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1CalendarId200>(
      {url: `https://api.yz13.ru/v1/calendar/${id}`, method: 'GET'
    },
      options);
    }
  
export const patchV1CalendarId = (
    id: string,
    patchV1CalendarIdBody: BodyType<PatchV1CalendarIdBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchV1CalendarId200>(
      {url: `https://api.yz13.ru/v1/calendar/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchV1CalendarIdBody
    },
      options);
    }
  
export const deleteV1CalendarId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<DeleteV1CalendarId200>(
      {url: `https://api.yz13.ru/v1/calendar/${id}`, method: 'DELETE'
    },
      options);
    }
  
export type GetV1PositionsLangResult = NonNullable<Awaited<ReturnType<typeof getV1PositionsLang>>>
export type GetV1PositionsLangPositionIdResult = NonNullable<Awaited<ReturnType<typeof getV1PositionsLangPositionId>>>
export type GetV1PricingResult = NonNullable<Awaited<ReturnType<typeof getV1Pricing>>>
export type GetV1PricingShortResult = NonNullable<Awaited<ReturnType<typeof getV1PricingShort>>>
export type GetV1UserUidResult = NonNullable<Awaited<ReturnType<typeof getV1UserUid>>>
export type PatchV1UserUidResult = NonNullable<Awaited<ReturnType<typeof patchV1UserUid>>>
export type GetV1AuthCurrentResult = NonNullable<Awaited<ReturnType<typeof getV1AuthCurrent>>>
export type GetV1AuthCurrentSessionResult = NonNullable<Awaited<ReturnType<typeof getV1AuthCurrentSession>>>
export type PostV1AuthLoginResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogin>>>
export type PostV1AuthSignupResult = NonNullable<Awaited<ReturnType<typeof postV1AuthSignup>>>
export type PostV1AuthLogoutResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogout>>>
export type GetV1RoomsIdResult = NonNullable<Awaited<ReturnType<typeof getV1RoomsId>>>
export type PostV1RoomsNewResult = NonNullable<Awaited<ReturnType<typeof postV1RoomsNew>>>
export type GetV1NewsNewsSourcesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsNewsSources>>>
export type GetV1NewsNewsSourcesSourceIdResult = NonNullable<Awaited<ReturnType<typeof getV1NewsNewsSourcesSourceId>>>
export type GetV1NewsCountryCodeSourcesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCountryCodeSources>>>
export type GetV1NewsArticlesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsArticles>>>
export type GetV1NewsArticlesSourceIdResult = NonNullable<Awaited<ReturnType<typeof getV1NewsArticlesSourceId>>>
export type PostV1NewsArticlesNewResult = NonNullable<Awaited<ReturnType<typeof postV1NewsArticlesNew>>>
export type GetV1NewsCountryCodeArticlesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCountryCodeArticles>>>
export type GetV1NewsArticleArticleIdResult = NonNullable<Awaited<ReturnType<typeof getV1NewsArticleArticleId>>>
export type GetV1NewsCodesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCodes>>>
export type GetV1NewsCategoriesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCategories>>>
export type PatchV1NewsRepatchResult = NonNullable<Awaited<ReturnType<typeof patchV1NewsRepatch>>>
export type PostV1NewsCacheClearResult = NonNullable<Awaited<ReturnType<typeof postV1NewsCacheClear>>>
export type PostV1EventsResult = NonNullable<Awaited<ReturnType<typeof postV1Events>>>
export type GetV1EventsUserUidResult = NonNullable<Awaited<ReturnType<typeof getV1EventsUserUid>>>
export type GetV1EventsIdResult = NonNullable<Awaited<ReturnType<typeof getV1EventsId>>>
export type PatchV1EventsIdResult = NonNullable<Awaited<ReturnType<typeof patchV1EventsId>>>
export type DeleteV1EventsIdResult = NonNullable<Awaited<ReturnType<typeof deleteV1EventsId>>>
export type GetV1StoreResult = NonNullable<Awaited<ReturnType<typeof getV1Store>>>
export type PostV1StoreResult = NonNullable<Awaited<ReturnType<typeof postV1Store>>>
export type GetV1StoreIdResult = NonNullable<Awaited<ReturnType<typeof getV1StoreId>>>
export type GetV1ScheduleUidResult = NonNullable<Awaited<ReturnType<typeof getV1ScheduleUid>>>
export type GetV1ScheduleUidAvailableResult = NonNullable<Awaited<ReturnType<typeof getV1ScheduleUidAvailable>>>
export type GetV1ChartsNewsResult = NonNullable<Awaited<ReturnType<typeof getV1ChartsNews>>>
export type GetV1CalendarUserUidDefaultResult = NonNullable<Awaited<ReturnType<typeof getV1CalendarUserUidDefault>>>
export type GetV1CalendarUserUidResult = NonNullable<Awaited<ReturnType<typeof getV1CalendarUserUid>>>
export type PostV1CalendarUserUidResult = NonNullable<Awaited<ReturnType<typeof postV1CalendarUserUid>>>
export type GetV1CalendarIdResult = NonNullable<Awaited<ReturnType<typeof getV1CalendarId>>>
export type PatchV1CalendarIdResult = NonNullable<Awaited<ReturnType<typeof patchV1CalendarId>>>
export type DeleteV1CalendarIdResult = NonNullable<Awaited<ReturnType<typeof deleteV1CalendarId>>>
