/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetV1AuthCurrent200,
  GetV1AuthCurrentSession200,
  GetV1NewsArticleArticleId200,
  GetV1NewsArticles200Item,
  GetV1NewsArticlesParams,
  GetV1NewsArticlesSourceId200Item,
  GetV1NewsCountryCodeArticles200Item,
  GetV1NewsCountryCodeArticlesParams,
  GetV1NewsCountryCodeSources200Item,
  GetV1NewsNewsSources200Item,
  GetV1NewsNewsSourcesParams,
  GetV1NewsNewsSourcesSourceId200,
  GetV1PositionsLang200Item,
  GetV1PositionsLangPositionId200,
  GetV1Pricing200Item,
  GetV1PricingShort200Item,
  GetV1RoomsId200,
  GetV1UserUid200,
  PatchV1NewsRepatch200,
  PatchV1UserUid200,
  PatchV1UserUidBody,
  PostV1AuthLogin200,
  PostV1AuthLoginBody,
  PostV1AuthLogout200,
  PostV1AuthSignup200,
  PostV1AuthSignupBody,
  PostV1NewsArticlesNew200,
  PostV1NewsArticlesNewBody,
  PostV1RoomsNew200,
  PostV1RoomsNewBody
} from '../types';

import { axios } from '../lib/custom-instance';
import type { BodyType } from '../lib/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getV1PositionsLang = (
    lang: 'en' | 'ru',
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1PositionsLang200Item[]>(
      {url: `https://localhost:3000/v1/positions/${lang}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1PositionsLangPositionId = (
    lang: 'en' | 'ru',
    positionId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1PositionsLangPositionId200>(
      {url: `https://localhost:3000/v1/positions/${lang}/${positionId}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1Pricing = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1Pricing200Item[]>(
      {url: `https://localhost:3000/v1/pricing`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1PricingShort = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1PricingShort200Item[]>(
      {url: `https://localhost:3000/v1/pricing/short`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1UserUid = (
    uid: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1UserUid200>(
      {url: `https://localhost:3000/v1/user/${uid}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const patchV1UserUid = (
    uid: string,
    patchV1UserUidBody: BodyType<PatchV1UserUidBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchV1UserUid200>(
      {url: `https://localhost:3000/v1/user/${uid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchV1UserUidBody
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1AuthCurrent = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1AuthCurrent200>(
      {url: `https://localhost:3000/v1/auth/current`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1AuthCurrentSession = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1AuthCurrentSession200>(
      {url: `https://localhost:3000/v1/auth/current/session`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const postV1AuthLogin = (
    postV1AuthLoginBody: BodyType<PostV1AuthLoginBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1AuthLogin200>(
      {url: `https://localhost:3000/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1AuthLoginBody
    },
      { withCredentials: true,  ...options});
    }
  
export const postV1AuthSignup = (
    postV1AuthSignupBody: BodyType<PostV1AuthSignupBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1AuthSignup200>(
      {url: `https://localhost:3000/v1/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1AuthSignupBody
    },
      { withCredentials: true,  ...options});
    }
  
export const postV1AuthLogout = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1AuthLogout200>(
      {url: `https://localhost:3000/v1/auth/logout`, method: 'POST'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1RoomsId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1RoomsId200>(
      {url: `https://localhost:3000/v1/rooms/${id}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const postV1RoomsNew = (
    postV1RoomsNewBody: BodyType<PostV1RoomsNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1RoomsNew200>(
      {url: `https://localhost:3000/v1/rooms/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1RoomsNewBody
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsNewsSources = (
    params?: GetV1NewsNewsSourcesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsNewsSources200Item[]>(
      {url: `https://localhost:3000/v1/news/news-sources`, method: 'GET',
        params
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsNewsSourcesSourceId = (
    sourceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsNewsSourcesSourceId200>(
      {url: `https://localhost:3000/v1/news/news-sources/${sourceId}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsCountryCodeSources = (
    code: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsCountryCodeSources200Item[]>(
      {url: `https://localhost:3000/v1/news/country/${code}/sources`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsArticles = (
    params?: GetV1NewsArticlesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsArticles200Item[]>(
      {url: `https://localhost:3000/v1/news/articles`, method: 'GET',
        params
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsArticlesSourceId = (
    sourceId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsArticlesSourceId200Item[]>(
      {url: `https://localhost:3000/v1/news/articles/${sourceId}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const postV1NewsArticlesNew = (
    postV1NewsArticlesNewBody: BodyType<PostV1NewsArticlesNewBody>,
 options?: SecondParameter<typeof axios>,) => {
      return axios<PostV1NewsArticlesNew200>(
      {url: `https://localhost:3000/v1/news/articles/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postV1NewsArticlesNewBody
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsCountryCodeArticles = (
    code: string,
    params?: GetV1NewsCountryCodeArticlesParams,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsCountryCodeArticles200Item[]>(
      {url: `https://localhost:3000/v1/news/country/${code}/articles`, method: 'GET',
        params
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsArticleArticleId = (
    articleId: string,
 options?: SecondParameter<typeof axios>,) => {
      return axios<GetV1NewsArticleArticleId200>(
      {url: `https://localhost:3000/v1/news/article/${articleId}`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsCodes = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string[]>(
      {url: `https://localhost:3000/v1/news/codes`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const getV1NewsCategories = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string[]>(
      {url: `https://localhost:3000/v1/news/categories`, method: 'GET'
    },
      { withCredentials: true,  ...options});
    }
  
export const patchV1NewsRepatch = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<PatchV1NewsRepatch200>(
      {url: `https://localhost:3000/v1/news/repatch`, method: 'PATCH'
    },
      { withCredentials: true,  ...options});
    }
  
export const postV1NewsCacheClear = (
    
 options?: SecondParameter<typeof axios>,) => {
      return axios<string>(
      {url: `https://localhost:3000/v1/news/cache/clear`, method: 'POST'
    },
      { withCredentials: true,  ...options});
    }
  
export type GetV1PositionsLangResult = NonNullable<Awaited<ReturnType<typeof getV1PositionsLang>>>
export type GetV1PositionsLangPositionIdResult = NonNullable<Awaited<ReturnType<typeof getV1PositionsLangPositionId>>>
export type GetV1PricingResult = NonNullable<Awaited<ReturnType<typeof getV1Pricing>>>
export type GetV1PricingShortResult = NonNullable<Awaited<ReturnType<typeof getV1PricingShort>>>
export type GetV1UserUidResult = NonNullable<Awaited<ReturnType<typeof getV1UserUid>>>
export type PatchV1UserUidResult = NonNullable<Awaited<ReturnType<typeof patchV1UserUid>>>
export type GetV1AuthCurrentResult = NonNullable<Awaited<ReturnType<typeof getV1AuthCurrent>>>
export type GetV1AuthCurrentSessionResult = NonNullable<Awaited<ReturnType<typeof getV1AuthCurrentSession>>>
export type PostV1AuthLoginResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogin>>>
export type PostV1AuthSignupResult = NonNullable<Awaited<ReturnType<typeof postV1AuthSignup>>>
export type PostV1AuthLogoutResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogout>>>
export type GetV1RoomsIdResult = NonNullable<Awaited<ReturnType<typeof getV1RoomsId>>>
export type PostV1RoomsNewResult = NonNullable<Awaited<ReturnType<typeof postV1RoomsNew>>>
export type GetV1NewsNewsSourcesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsNewsSources>>>
export type GetV1NewsNewsSourcesSourceIdResult = NonNullable<Awaited<ReturnType<typeof getV1NewsNewsSourcesSourceId>>>
export type GetV1NewsCountryCodeSourcesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCountryCodeSources>>>
export type GetV1NewsArticlesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsArticles>>>
export type GetV1NewsArticlesSourceIdResult = NonNullable<Awaited<ReturnType<typeof getV1NewsArticlesSourceId>>>
export type PostV1NewsArticlesNewResult = NonNullable<Awaited<ReturnType<typeof postV1NewsArticlesNew>>>
export type GetV1NewsCountryCodeArticlesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCountryCodeArticles>>>
export type GetV1NewsArticleArticleIdResult = NonNullable<Awaited<ReturnType<typeof getV1NewsArticleArticleId>>>
export type GetV1NewsCodesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCodes>>>
export type GetV1NewsCategoriesResult = NonNullable<Awaited<ReturnType<typeof getV1NewsCategories>>>
export type PatchV1NewsRepatchResult = NonNullable<Awaited<ReturnType<typeof patchV1NewsRepatch>>>
export type PostV1NewsCacheClearResult = NonNullable<Awaited<ReturnType<typeof postV1NewsCacheClear>>>
