/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type DeletePinsV1TagsTagId200 = {
  created_at: string;
  id: string;
  label: string;
} | null;
