/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteCalendarV1SchedulesScheduleId200MondayItem } from './delete-calendar-v1-schedules-schedule-id200-monday-item';
import type { DeleteCalendarV1SchedulesScheduleId200TuesdayItem } from './delete-calendar-v1-schedules-schedule-id200-tuesday-item';
import type { DeleteCalendarV1SchedulesScheduleId200WednesdayItem } from './delete-calendar-v1-schedules-schedule-id200-wednesday-item';
import type { DeleteCalendarV1SchedulesScheduleId200ThursdayItem } from './delete-calendar-v1-schedules-schedule-id200-thursday-item';
import type { DeleteCalendarV1SchedulesScheduleId200FridayItem } from './delete-calendar-v1-schedules-schedule-id200-friday-item';
import type { DeleteCalendarV1SchedulesScheduleId200SaturdayItem } from './delete-calendar-v1-schedules-schedule-id200-saturday-item';
import type { DeleteCalendarV1SchedulesScheduleId200SundayItem } from './delete-calendar-v1-schedules-schedule-id200-sunday-item';

export type DeleteCalendarV1SchedulesScheduleId200 = {
  uid: string;
  calendar_id: string;
  monday: DeleteCalendarV1SchedulesScheduleId200MondayItem[];
  tuesday: DeleteCalendarV1SchedulesScheduleId200TuesdayItem[];
  wednesday: DeleteCalendarV1SchedulesScheduleId200WednesdayItem[];
  thursday: DeleteCalendarV1SchedulesScheduleId200ThursdayItem[];
  friday: DeleteCalendarV1SchedulesScheduleId200FridayItem[];
  saturday: DeleteCalendarV1SchedulesScheduleId200SaturdayItem[];
  sunday: DeleteCalendarV1SchedulesScheduleId200SundayItem[];
  durations: string[];
};
