/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type DeleteNotesV1NoteId200 = {
  id: string;
  created_at: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  content: string | null;
  /** @nullable */
  owner: string | null;
  /** @nullable */
  pinned: boolean | null;
  /** @nullable */
  public: boolean | null;
  /** @nullable */
  shared_with: string[] | null;
  /** @nullable */
  workspace_id: string | null;
  /** @nullable */
  tags: string[] | null;
} | null;
