/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetNewsV1Search502ItemImg } from './get-news-v1-search502-item-img';
import type { GetNewsV1Search502ItemNewsSource } from './get-news-v1-search502-item-news-source';

export type GetNewsV1Search502Item = {
  id: string;
  title: string;
  /** @nullable */
  description: string | null;
  url: string;
  /** @nullable */
  author: string | null;
  published_at: string;
  /** @nullable */
  source: string | null;
  /** @nullable */
  source_id: string | null;
  method: string;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  content: string | null;
  /** @nullable */
  last_checked_at: string | null;
  /** @nullable */
  img?: GetNewsV1Search502ItemImg;
  /** @nullable */
  news_source: GetNewsV1Search502ItemNewsSource;
};
