/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetTagsV1502Item = {
  id: string;
  created_at: string;
  /** @nullable */
  tag: string | null;
  /** @nullable */
  workspace_id: string | null;
};
