/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetLinkV1Id200User } from './get-link-v1-id200-user';
import type { GetLinkV1Id200ItemsItem } from './get-link-v1-id200-items-item';
import type { GetLinkV1Id200Socials } from './get-link-v1-id200-socials';
import type { GetLinkV1Id200Actions } from './get-link-v1-id200-actions';

/**
 * @nullable
 */
export type GetLinkV1Id200 = {
  /** @nullable */
  profession?: string | null;
  user: GetLinkV1Id200User;
  items: GetLinkV1Id200ItemsItem[];
  socials?: GetLinkV1Id200Socials;
  actions?: GetLinkV1Id200Actions;
} | null;
