/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetCalendarV1EventsUserId502ItemType = typeof GetCalendarV1EventsUserId502ItemType[keyof typeof GetCalendarV1EventsUserId502ItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCalendarV1EventsUserId502ItemType = {
  event: 'event',
  appointment: 'appointment',
} as const;
