/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1RoomsId500Error } from './get-v1-rooms-id500-error';

export type GetV1RoomsId500 = {
  /** @nullable */
  error?: GetV1RoomsId500Error;
};
