/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetCalendarV1SchedulesUserIdAvailabilityParams = {
/**
 * Check availability for specific date
 */
date?: string;
/**
 * Include past availability slots
 */
include_past?: string;
};
