/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetStoreV1Id200Icon } from './get-store-v1-id200-icon';
import type { GetStoreV1Id200VersionsItem } from './get-store-v1-id200-versions-item';
import type { GetStoreV1Id200AttachmentsItem } from './get-store-v1-id200-attachments-item';

/**
 * @nullable
 */
export type GetStoreV1Id200 = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  icon?: GetStoreV1Id200Icon;
  publisher_id: string;
  publisher_type: string;
  /** @nullable */
  published_version: string | null;
  /** @nullable */
  type: string | null;
  /** @nullable */
  stage: string | null;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  public_url: string | null;
  /** @nullable */
  versions: GetStoreV1Id200VersionsItem[] | null;
  /** @nullable */
  is_archived: boolean | null;
  created_at: string;
  updated_at: string;
  /** @nullable */
  attachments: GetStoreV1Id200AttachmentsItem[] | null;
  /** @nullable */
  category: number | null;
} | null;
