/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1AuthCurrent200IdentitiesItem } from './get-v1-auth-current200-identities-item';

/**
 * @nullable
 */
export type GetV1AuthCurrent200 = {
  id: string;
  email?: string;
  email_confirmed_at?: string;
  phone?: string;
  created_at: string;
  updated_at?: string;
  last_signin_at?: string;
  role: string;
  username: string;
  /** @nullable */
  avatar_url: string | null;
  identities: GetV1AuthCurrent200IdentitiesItem[];
  position?: string;
} | null;
