/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type GetPinsV1PinsPinIdAnchor502 = {
  board_id: string;
  created_at: string;
  pin_id: string;
  user_id: string;
} | null;
