/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetPricingV1200ItemDetailsItem } from './get-pricing-v1200-item-details-item';

export type GetPricingV1200Item = {
  id: number;
  created_at: string;
  /** @nullable */
  description: string | null;
  details: GetPricingV1200ItemDetailsItem[];
  /** @nullable */
  name: string | null;
  price: number;
  /** @nullable */
  type: string | null;
  duration: number[];
  discount: number;
};
