/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type GetNewsV1ContentId200 = {
  content?: string;
} | null;
