/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetLinkV1Id200ItemsItem = {
  url: string;
  label: string;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  description?: string | null;
};
