/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetWorkspacesV1400Item = {
  id: string;
  created_at: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  owner: string;
  /** @nullable */
  public: boolean | null;
  /** @nullable */
  shared_with: string[] | null;
  /** @nullable */
  tags: string[] | null;
};
