/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1NewsNewsSources500Item = {
  id: string;
  name: string;
  url: string;
  country_code: string;
  /** @nullable */
  rss: string | null;
  /** @nullable */
  created_at: string | null;
};
