/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetCalendarV1SchedulesUserId200ItemMondayItem } from './get-calendar-v1-schedules-user-id200-item-monday-item';
import type { GetCalendarV1SchedulesUserId200ItemTuesdayItem } from './get-calendar-v1-schedules-user-id200-item-tuesday-item';
import type { GetCalendarV1SchedulesUserId200ItemWednesdayItem } from './get-calendar-v1-schedules-user-id200-item-wednesday-item';
import type { GetCalendarV1SchedulesUserId200ItemThursdayItem } from './get-calendar-v1-schedules-user-id200-item-thursday-item';
import type { GetCalendarV1SchedulesUserId200ItemFridayItem } from './get-calendar-v1-schedules-user-id200-item-friday-item';
import type { GetCalendarV1SchedulesUserId200ItemSaturdayItem } from './get-calendar-v1-schedules-user-id200-item-saturday-item';
import type { GetCalendarV1SchedulesUserId200ItemSundayItem } from './get-calendar-v1-schedules-user-id200-item-sunday-item';

export type GetCalendarV1SchedulesUserId200Item = {
  uid: string;
  calendar_id: string;
  monday: GetCalendarV1SchedulesUserId200ItemMondayItem[];
  tuesday: GetCalendarV1SchedulesUserId200ItemTuesdayItem[];
  wednesday: GetCalendarV1SchedulesUserId200ItemWednesdayItem[];
  thursday: GetCalendarV1SchedulesUserId200ItemThursdayItem[];
  friday: GetCalendarV1SchedulesUserId200ItemFridayItem[];
  saturday: GetCalendarV1SchedulesUserId200ItemSaturdayItem[];
  sunday: GetCalendarV1SchedulesUserId200ItemSundayItem[];
  durations: string[];
};
