/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetPricingV1Id200DetailsItem } from './get-pricing-v1-id200-details-item';

/**
 * @nullable
 */
export type GetPricingV1Id200 = {
  id: number;
  created_at: string;
  /** @nullable */
  description: string | null;
  details: GetPricingV1Id200DetailsItem[];
  /** @nullable */
  name: string | null;
  price: number;
  /** @nullable */
  type: string | null;
  duration: number[];
  discount: number;
} | null;
