/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetTasksV1200Item = {
  /** @nullable */
  checked: boolean | null;
  /** @nullable */
  checked_at: string | null;
  /** @nullable */
  checked_by: string | null;
  created_at: string;
  id: string;
  /** @nullable */
  owner: string | null;
  priority: number;
  tag: string;
  /** @nullable */
  updated_at: string | null;
  /** @nullable */
  workspace_id: string | null;
};
