/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1EventsId200Type = typeof GetV1EventsId200Type[keyof typeof GetV1EventsId200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetV1EventsId200Type = {
  event: 'event',
  appointment: 'appointment',
} as const;
