/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type GetLinksV1Id200 = {
  id: string;
  created_at: string;
  to: string;
} | null;
