/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetPinsV1PinsPinIdSimilar200ItemOwner = {
  /** @nullable */
  avatar_url: string | null;
  created_at: string;
  /** @nullable */
  full_name: string | null;
  /** @nullable */
  updated_at: string | null;
  user_id: string;
  /** @nullable */
  username: string | null;
};
