/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetLinkV1Id200ActionsSecondaryType } from './get-link-v1-id200-actions-secondary-type';

export type GetLinkV1Id200ActionsSecondary = {
  label: string;
  /** @nullable */
  icon?: string | null;
  type?: GetLinkV1Id200ActionsSecondaryType;
  value: string;
  disabled?: boolean;
};
