/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { GetPinsV1PinsPinIdSimilar502ItemOwner } from './get-pins-v1-pins-pin-id-similar502-item-owner';

export type GetPinsV1PinsPinIdSimilar502Item = {
  /** @nullable */
  board_id?: string | null;
  created_at: string;
  /** @nullable */
  description?: string | null;
  id: string;
  name: string;
  /** @nullable */
  source_url?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  updated_at?: string | null;
  owner: GetPinsV1PinsPinIdSimilar502ItemOwner;
  /** @nullable */
  attachment: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  thumbnail: string | null;
};
