/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetLinkV1Id200SocialsTelegram } from './get-link-v1-id200-socials-telegram';
import type { GetLinkV1Id200SocialsGithub } from './get-link-v1-id200-socials-github';
import type { GetLinkV1Id200SocialsX } from './get-link-v1-id200-socials-x';
import type { GetLinkV1Id200SocialsFacebook } from './get-link-v1-id200-socials-facebook';
import type { GetLinkV1Id200SocialsInstagram } from './get-link-v1-id200-socials-instagram';
import type { GetLinkV1Id200SocialsYoutube } from './get-link-v1-id200-socials-youtube';

export type GetLinkV1Id200Socials = {
  telegram?: GetLinkV1Id200SocialsTelegram;
  github?: GetLinkV1Id200SocialsGithub;
  x?: GetLinkV1Id200SocialsX;
  facebook?: GetLinkV1Id200SocialsFacebook;
  instagram?: GetLinkV1Id200SocialsInstagram;
  youtube?: GetLinkV1Id200SocialsYoutube;
};
