/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetLinkV1Id200ActionsPrimary } from './get-link-v1-id200-actions-primary';
import type { GetLinkV1Id200ActionsSecondary } from './get-link-v1-id200-actions-secondary';

export type GetLinkV1Id200Actions = {
  primary?: GetLinkV1Id200ActionsPrimary;
  secondary?: GetLinkV1Id200ActionsSecondary;
};
