/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { GetNewsV1Recent200ItemThumbnail } from './get-news-v1-recent200-item-thumbnail';

export type GetNewsV1Recent200Item = {
  id: string;
  published_at: string;
  source_id: string;
  title: string;
  /** @nullable */
  description: string | null;
  url: string;
  method: string;
  authors: string[];
  thumbnail: GetNewsV1Recent200ItemThumbnail;
  tags: string[];
  summary: string;
  /** @nullable */
  last_checked_at: string | null;
};
