/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetCalendarV1SchedulesUserId502ItemMondayItem } from './get-calendar-v1-schedules-user-id502-item-monday-item';
import type { GetCalendarV1SchedulesUserId502ItemTuesdayItem } from './get-calendar-v1-schedules-user-id502-item-tuesday-item';
import type { GetCalendarV1SchedulesUserId502ItemWednesdayItem } from './get-calendar-v1-schedules-user-id502-item-wednesday-item';
import type { GetCalendarV1SchedulesUserId502ItemThursdayItem } from './get-calendar-v1-schedules-user-id502-item-thursday-item';
import type { GetCalendarV1SchedulesUserId502ItemFridayItem } from './get-calendar-v1-schedules-user-id502-item-friday-item';
import type { GetCalendarV1SchedulesUserId502ItemSaturdayItem } from './get-calendar-v1-schedules-user-id502-item-saturday-item';
import type { GetCalendarV1SchedulesUserId502ItemSundayItem } from './get-calendar-v1-schedules-user-id502-item-sunday-item';

export type GetCalendarV1SchedulesUserId502Item = {
  uid: string;
  calendar_id: string;
  monday: GetCalendarV1SchedulesUserId502ItemMondayItem[];
  tuesday: GetCalendarV1SchedulesUserId502ItemTuesdayItem[];
  wednesday: GetCalendarV1SchedulesUserId502ItemWednesdayItem[];
  thursday: GetCalendarV1SchedulesUserId502ItemThursdayItem[];
  friday: GetCalendarV1SchedulesUserId502ItemFridayItem[];
  saturday: GetCalendarV1SchedulesUserId502ItemSaturdayItem[];
  sunday: GetCalendarV1SchedulesUserId502ItemSundayItem[];
  durations: string[];
};
