/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { GetPinsV1BoardsBoardIdAnchors502ItemPin } from './get-pins-v1-boards-board-id-anchors502-item-pin';
import type { GetPinsV1BoardsBoardIdAnchors502ItemBoard } from './get-pins-v1-boards-board-id-anchors502-item-board';
import type { GetPinsV1BoardsBoardIdAnchors502ItemOwner } from './get-pins-v1-boards-board-id-anchors502-item-owner';

export type GetPinsV1BoardsBoardIdAnchors502Item = {
  pin: GetPinsV1BoardsBoardIdAnchors502ItemPin;
  board: GetPinsV1BoardsBoardIdAnchors502ItemBoard;
  owner: GetPinsV1BoardsBoardIdAnchors502ItemOwner;
};
