/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1PricingShort400Item = {
  id: number;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  price: number;
  /** @nullable */
  type: string | null;
  created_at: string;
};
