/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetUsageV1502Item = {
  id: number;
  created_at: string;
  /** @nullable */
  path: string | null;
  /** @nullable */
  status_code: number | null;
  /** @nullable */
  duration: number | null;
  /** @nullable */
  method: string | null;
  /** @nullable */
  search_params: string | null;
  /** @nullable */
  request_id: string | null;
};
