/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetLinkV1Id200User = {
  /** @nullable */
  fullname?: string | null;
  username: string;
  /** @nullable */
  avatar_url: string | null;
  /** @nullable */
  description?: string | null;
};
