/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1EventsUserUid200ItemType = typeof GetV1EventsUserUid200ItemType[keyof typeof GetV1EventsUserUid200ItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetV1EventsUserUid200ItemType = {
  event: 'event',
  appointment: 'appointment',
} as const;
