/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetV1ScheduleUidAvailable200 = unknown | null;
