/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetAuthV1Me200IdentitiesItem } from './get-auth-v1-me200-identities-item';

/**
 * @nullable
 */
export type GetAuthV1Me200 = {
  id: string;
  email?: string;
  email_confirmed_at?: string;
  phone?: string;
  created_at: string;
  updated_at?: string;
  last_signin_at?: string;
  role: string;
  username: string;
  /** @nullable */
  avatar_url: string | null;
  identities: GetAuthV1Me200IdentitiesItem[];
  position?: string;
} | null;
