/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetStoreV1200ItemIcon } from './get-store-v1200-item-icon';
import type { GetStoreV1200ItemVersionsItem } from './get-store-v1200-item-versions-item';
import type { GetStoreV1200ItemAttachmentsItem } from './get-store-v1200-item-attachments-item';

export type GetStoreV1200Item = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  icon?: GetStoreV1200ItemIcon;
  publisher_id: string;
  publisher_type: string;
  /** @nullable */
  published_version: string | null;
  /** @nullable */
  type: string | null;
  /** @nullable */
  stage: string | null;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  public_url: string | null;
  /** @nullable */
  versions: GetStoreV1200ItemVersionsItem[] | null;
  /** @nullable */
  is_archived: boolean | null;
  created_at: string;
  updated_at: string;
  /** @nullable */
  attachments: GetStoreV1200ItemAttachmentsItem[] | null;
  /** @nullable */
  category: number | null;
};
