/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1Pricing200ItemDetailsItem } from './get-v1-pricing200-item-details-item';

export type GetV1Pricing200Item = {
  id: number;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  price: number;
  /** @nullable */
  type: string | null;
  details: GetV1Pricing200ItemDetailsItem[];
  created_at: string;
};
