/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

export type GetBlogV1Drafts200Item = {
  name: string;
  id: string;
  updated_at: string;
  created_at: string;
  last_accessed_at: string;
};
