/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetLinkV1Id200ActionsPrimaryType = typeof GetLinkV1Id200ActionsPrimaryType[keyof typeof GetLinkV1Id200ActionsPrimaryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLinkV1Id200ActionsPrimaryType = {
  link: 'link',
  copy: 'copy',
  custom: 'custom',
} as const;
