/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { GetBlogV1Posts200ItemAttachmentsItem } from './get-blog-v1-posts200-item-attachments-item';

export type GetBlogV1Posts200Item = {
  attachments: GetBlogV1Posts200ItemAttachmentsItem[];
  authors: string[];
  categories: string[];
  date: string;
  id: string;
  pinned: boolean;
  /** @nullable */
  summary: string | null;
  title: string;
};
