/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetPinsV1BoardsAll502Item = {
  authors: string[];
  created_at: string;
  id: string;
  name: string;
  owner: string;
  public: boolean;
  /** @nullable */
  updated_at?: string | null;
};
