/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type GetPinsV1PinsPinIdAnchor502 = {
  board_id: string;
  created_at: string;
  pin_id: string;
  user_id: string;
} | null;
