/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type GetStoreV1Id200VersionsItem = unknown | null;
