/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type GetPositionsV1LangPositionId200 = {
  id: string;
  name: string;
  description?: string;
  lang: string;
  created_at: string;
  updated_at?: string;
} | null;
