/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { GetPinsV1BoardsBoardIdAnchors200ItemPin } from './get-pins-v1-boards-board-id-anchors200-item-pin';
import type { GetPinsV1BoardsBoardIdAnchors200ItemBoard } from './get-pins-v1-boards-board-id-anchors200-item-board';
import type { GetPinsV1BoardsBoardIdAnchors200ItemOwner } from './get-pins-v1-boards-board-id-anchors200-item-owner';

export type GetPinsV1BoardsBoardIdAnchors200Item = {
  pin: GetPinsV1BoardsBoardIdAnchors200ItemPin;
  board: GetPinsV1BoardsBoardIdAnchors200ItemBoard;
  owner: GetPinsV1BoardsBoardIdAnchors200ItemOwner;
};
