/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1Store200ItemIcon } from './get-v1-store200-item-icon';
import type { GetV1Store200ItemVersionsItem } from './get-v1-store200-item-versions-item';

export type GetV1Store200Item = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  icon?: GetV1Store200ItemIcon;
  publisher_id: string;
  publisher_type: string;
  /** @nullable */
  type: string | null;
  /** @nullable */
  stage: string | null;
  /** @nullable */
  categories: string[] | null;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  public_url: string | null;
  /** @nullable */
  published_version: string | null;
  /** @nullable */
  versions: GetV1Store200ItemVersionsItem[] | null;
  /** @nullable */
  is_archived: boolean | null;
  created_at: string;
  updated_at: string;
};
