/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetBlogV1Posts502ItemAttachmentsItem } from './get-blog-v1-posts502-item-attachments-item';

export type GetBlogV1Posts502Item = {
  attachments: GetBlogV1Posts502ItemAttachmentsItem[];
  authors: string[];
  categories: string[];
  date: string;
  id: string;
  pinned: boolean;
  /** @nullable */
  summary: string | null;
  title: string;
};
