/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1EventsUserUidParams = {
date_start?: string;
date_end?: string;
date?: string;
limit?: string;
type?: string;
};
