/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetBlogV1Drafts200Item = {
  name: string;
  id: string;
  updated_at: string;
  created_at: string;
  last_accessed_at: string;
};
