/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetPositionsV1Lang200Item = {
  id: string;
  name: string;
  description?: string;
  lang: string;
  created_at: string;
  updated_at?: string;
};
