/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type GetNewsV1Params = {
/**
 * Offset for pagination
 */
offset?: string;
/**
 * Date filter (yyyy-MM-dd format)
 */
date?: string;
};
