/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { GetPinsV1PinsSearch500ItemOwner } from './get-pins-v1-pins-search500-item-owner';

export type GetPinsV1PinsSearch500Item = {
  /** @nullable */
  board_id?: string | null;
  created_at: string;
  /** @nullable */
  description?: string | null;
  id: string;
  name: string;
  /** @nullable */
  source_url?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  updated_at?: string | null;
  owner: GetPinsV1PinsSearch500ItemOwner;
  /** @nullable */
  attachment: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  thumbnail: string | null;
};
