/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

export type GetPinsV1BoardsBoardIdAnchors200ItemOwner = {
  /** @nullable */
  avatar_url: string | null;
  created_at: string;
  /** @nullable */
  full_name: string | null;
  /** @nullable */
  updated_at: string | null;
  user_id: string;
  /** @nullable */
  username: string | null;
};
