/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type GetNewsV1Recent200ItemNewsSource = {
  id: string;
  name: string;
  url: string;
  country_code: string;
  /** @nullable */
  rss: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  last_checked: string | null;
} | null;
