/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchV1UserUid200IdentitiesItem } from './patch-v1-user-uid200-identities-item';

export type PatchV1UserUid200 = {
  id: string;
  email?: string;
  email_confirmed_at?: string;
  phone?: string;
  created_at: string;
  updated_at?: string;
  last_signin_at?: string;
  role: string;
  username: string;
  /** @nullable */
  avatar_url: string | null;
  identities: PatchV1UserUid200IdentitiesItem[];
  position?: string;
};
