/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PatchPinsV1PinsPinId200Owner } from './patch-pins-v1-pins-pin-id200-owner';

/**
 * @nullable
 */
export type PatchPinsV1PinsPinId200 = {
  /** @nullable */
  board_id?: string | null;
  created_at: string;
  /** @nullable */
  description?: string | null;
  id: string;
  name: string;
  /** @nullable */
  source_url?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  updated_at?: string | null;
  owner: PatchPinsV1PinsPinId200Owner;
  /** @nullable */
  attachment: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  thumbnail: string | null;
} | null;
