/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchV1UserUidBodyData } from './patch-v1-user-uid-body-data';

export type PatchV1UserUidBody = {
  email?: string;
  phone?: string;
  /** @minLength 6 */
  password?: string;
  data?: PatchV1UserUidBodyData;
};
