/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type PatchV1EventsIdBodyType = typeof PatchV1EventsIdBodyType[keyof typeof PatchV1EventsIdBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchV1EventsIdBodyType = {
  event: 'event',
  appointment: 'appointment',
} as const;
