/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchV1EventsId200Type } from './patch-v1-events-id200-type';

/**
 * @nullable
 */
export type PatchV1EventsId200 = {
  id: string;
  calendar_id: string;
  organizer_id: string;
  summary: string;
  /** @nullable */
  description: string | null;
  date_start: string;
  date_end: string;
  /** @nullable */
  all_day: boolean | null;
  /** @nullable */
  location: string | null;
  /** @nullable */
  geo_lat: number | null;
  /** @nullable */
  geo_lon: number | null;
  /** @nullable */
  duration: string | null;
  type: PatchV1EventsId200Type;
  /** @nullable */
  status: string | null;
  /** @nullable */
  class: string | null;
  /** @nullable */
  categories: string[] | null;
  /** @nullable */
  guests: string[] | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  conference_id: string | null;
  /** @nullable */
  recurrence_id: string | null;
  /** @nullable */
  recurrence_rule: string | null;
  /** @nullable */
  sequence: number | null;
  /** @nullable */
  created: string | null;
  /** @nullable */
  last_modified: string | null;
} | null;
