/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1AuthLogout200Error } from './post-v1-auth-logout200-error';

export type PostV1AuthLogout200 = {
  status?: boolean;
  /** @nullable */
  error?: PostV1AuthLogout200Error;
};
