/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PostCalendarV1EventsBodyType = typeof PostCalendarV1EventsBodyType[keyof typeof PostCalendarV1EventsBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCalendarV1EventsBodyType = {
  event: 'event',
  appointment: 'appointment',
} as const;
