/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { PostAuthV1Register200IdentitiesItem } from './post-auth-v1-register200-identities-item';

/**
 * @nullable
 */
export type PostAuthV1Register200 = {
  id: string;
  email?: string;
  email_confirmed_at?: string;
  phone?: string;
  created_at: string;
  updated_at?: string;
  last_signin_at?: string;
  role: string;
  username: string;
  /** @nullable */
  avatar_url: string | null;
  identities: PostAuthV1Register200IdentitiesItem[];
  position?: string;
} | null;
