/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type PostClicksV1Track200 = {
  id: number;
  created_at: string;
  /** @nullable */
  domain: string | null;
  path: string;
} | null;
