/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type PostBlogV1Drafts200 = {
  id: string;
  path: string;
  fullPath: string;
} | null;
