/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PostPinsV1PinsNewBody = {
  /** @nullable */
  board_id?: string | null;
  /** @nullable */
  description?: string | null;
  name: string;
  /** @nullable */
  source_url?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  attachment: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  thumbnail: string | null;
};
