/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type PostCalendarV1Slots200 = {
  id: string;
  owner_id: string;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
  duration: string;
  name: string;
  /** @nullable */
  description: string | null;
} | null;
