/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type PostPinsV1BoardsNew502 = {
  authors: string[];
  created_at: string;
  id: string;
  name: string;
  owner: string;
  public: boolean;
  /** @nullable */
  updated_at?: string | null;
} | null;
