/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PostCalendarV1Schedules200MondayItem } from './post-calendar-v1-schedules200-monday-item';
import type { PostCalendarV1Schedules200TuesdayItem } from './post-calendar-v1-schedules200-tuesday-item';
import type { PostCalendarV1Schedules200WednesdayItem } from './post-calendar-v1-schedules200-wednesday-item';
import type { PostCalendarV1Schedules200ThursdayItem } from './post-calendar-v1-schedules200-thursday-item';
import type { PostCalendarV1Schedules200FridayItem } from './post-calendar-v1-schedules200-friday-item';
import type { PostCalendarV1Schedules200SaturdayItem } from './post-calendar-v1-schedules200-saturday-item';
import type { PostCalendarV1Schedules200SundayItem } from './post-calendar-v1-schedules200-sunday-item';

/**
 * @nullable
 */
export type PostCalendarV1Schedules200 = {
  uid: string;
  calendar_id: string;
  monday: PostCalendarV1Schedules200MondayItem[];
  tuesday: PostCalendarV1Schedules200TuesdayItem[];
  wednesday: PostCalendarV1Schedules200WednesdayItem[];
  thursday: PostCalendarV1Schedules200ThursdayItem[];
  friday: PostCalendarV1Schedules200FridayItem[];
  saturday: PostCalendarV1Schedules200SaturdayItem[];
  sunday: PostCalendarV1Schedules200SundayItem[];
  durations: string[];
} | null;
