/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PostPinsV1BoardsBoardIdAnchorsPinId409Pin } from './post-pins-v1-boards-board-id-anchors-pin-id409-pin';
import type { PostPinsV1BoardsBoardIdAnchorsPinId409Board } from './post-pins-v1-boards-board-id-anchors-pin-id409-board';
import type { PostPinsV1BoardsBoardIdAnchorsPinId409Owner } from './post-pins-v1-boards-board-id-anchors-pin-id409-owner';

/**
 * @nullable
 */
export type PostPinsV1BoardsBoardIdAnchorsPinId409 = {
  pin: PostPinsV1BoardsBoardIdAnchorsPinId409Pin;
  board: PostPinsV1BoardsBoardIdAnchorsPinId409Board;
  owner: PostPinsV1BoardsBoardIdAnchorsPinId409Owner;
} | null;
