/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1NewsArticlesNewChunk401ItemImg } from './post-v1-news-articles-new-chunk401-item-img';

export type PostV1NewsArticlesNewChunk401Item = {
  id: string;
  title: string;
  /** @nullable */
  description: string | null;
  url: string;
  /** @nullable */
  author: string | null;
  published_at: string;
  /** @nullable */
  source: string | null;
  /** @nullable */
  source_id: string | null;
  method: string;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  img: PostV1NewsArticlesNewChunk401ItemImg;
};
