/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { PostPinsV1BoardsBoardIdAnchorsPinId200Pin } from './post-pins-v1-boards-board-id-anchors-pin-id200-pin';
import type { PostPinsV1BoardsBoardIdAnchorsPinId200Board } from './post-pins-v1-boards-board-id-anchors-pin-id200-board';
import type { PostPinsV1BoardsBoardIdAnchorsPinId200Owner } from './post-pins-v1-boards-board-id-anchors-pin-id200-owner';

/**
 * @nullable
 */
export type PostPinsV1BoardsBoardIdAnchorsPinId200 = {
  pin: PostPinsV1BoardsBoardIdAnchorsPinId200Pin;
  board: PostPinsV1BoardsBoardIdAnchorsPinId200Board;
  owner: PostPinsV1BoardsBoardIdAnchorsPinId200Owner;
} | null;
