/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PostCalendarV1EventsBodyType } from './post-calendar-v1-events-body-type';

export type PostCalendarV1EventsBody = {
  calendar_id: string;
  organizer_id?: string;
  summary: string;
  /** @nullable */
  description: string | null;
  date_start: string;
  date_end: string;
  /** @nullable */
  all_day?: boolean | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  geo_lat?: number | null;
  /** @nullable */
  geo_lon?: number | null;
  /** @nullable */
  duration?: string | null;
  type?: PostCalendarV1EventsBodyType;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  class?: string | null;
  /** @nullable */
  categories?: string[] | null;
  /** @nullable */
  guests?: string[] | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  conference_id?: string | null;
  /** @nullable */
  recurrence_id?: string | null;
  /** @nullable */
  recurrence_rule?: string | null;
  /** @nullable */
  sequence?: number | null;
};
