/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1AuthSignup200User } from './post-v1-auth-signup200-user';

export type PostV1AuthSignup200 = {
  /** @nullable */
  user?: PostV1AuthSignup200User;
  error?: string;
};
