/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type PostCalendarV1CalendarsUserId200 = {
  id: string;
  user_id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  timezone: string | null;
  /** @nullable */
  is_default: boolean | null;
  /** @nullable */
  is_public: boolean | null;
  /** @nullable */
  visible: boolean | null;
  /** @nullable */
  shared_with: string[] | null;
  created_at: string;
} | null;
