/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1AuthSignupBodyOptionsData = {
  username?: string;
  /** @nullable */
  avatar_url?: string | null;
  position?: string;
  role?: string;
};
