/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1RoomsNewBody = {
  max_members: number;
  name: string;
  public: boolean;
  owner: string;
};
