/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

export type PostPinsV1PinsPinIdUpload200 = {
  id: string;
  path: string;
  fullPath: string;
};
