/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PostBlogV1PostsBody = {
  /** Markdown file to upload */
  file: Blob;
  /** Optional name for the file (without .md extension) */
  name?: string;
};
