/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1Events200Type = typeof PostV1Events200Type[keyof typeof PostV1Events200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostV1Events200Type = {
  event: 'event',
  appointment: 'appointment',
} as const;
