/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */

export type PostBlogV1PostsBody = {
  /** Markdown file to upload */
  file: Blob;
  /** Optional name for the file (without .md extension) */
  name?: string;
};
