/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */

export type PostV1EventsBodyType = typeof PostV1EventsBodyType[keyof typeof PostV1EventsBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostV1EventsBodyType = {
  event: 'event',
  appointment: 'appointment',
} as const;
