/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { PostPinsV1PinsNew200Owner } from './post-pins-v1-pins-new200-owner';

/**
 * @nullable
 */
export type PostPinsV1PinsNew200 = {
  /** @nullable */
  board_id?: string | null;
  created_at: string;
  /** @nullable */
  description?: string | null;
  id: string;
  name: string;
  /** @nullable */
  source_url?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  updated_at?: string | null;
  owner: PostPinsV1PinsNew200Owner;
  /** @nullable */
  attachment: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  thumbnail: string | null;
} | null;
