/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1AuthLogout500Error } from './post-v1-auth-logout500-error';

export type PostV1AuthLogout500 = {
  /** @nullable */
  error?: PostV1AuthLogout500Error;
};
