/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PostPinsV1BoardsBoardIdAnchorsPinId200PinOwner } from './post-pins-v1-boards-board-id-anchors-pin-id200-pin-owner';

export type PostPinsV1BoardsBoardIdAnchorsPinId200Pin = {
  /** @nullable */
  board_id?: string | null;
  created_at: string;
  /** @nullable */
  description?: string | null;
  id: string;
  name: string;
  /** @nullable */
  source_url?: string | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  updated_at?: string | null;
  owner: PostPinsV1BoardsBoardIdAnchorsPinId200PinOwner;
  /** @nullable */
  attachment: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  thumbnail: string | null;
};
