/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1Store200Icon } from './post-v1-store200-icon';
import type { PostV1Store200VersionsItem } from './post-v1-store200-versions-item';

/**
 * @nullable
 */
export type PostV1Store200 = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  icon?: PostV1Store200Icon;
  publisher_id: string;
  publisher_type: string;
  /** @nullable */
  type: string | null;
  /** @nullable */
  stage: string | null;
  /** @nullable */
  categories: string[] | null;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  public_url: string | null;
  /** @nullable */
  published_version: string | null;
  /** @nullable */
  versions: PostV1Store200VersionsItem[] | null;
  /** @nullable */
  is_archived: boolean | null;
  created_at: string;
  updated_at: string;
} | null;
