/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * YZ13 API
 * It's YZ13 API
 * OpenAPI spec version: 1.0.0
 */
import type { PostV1StoreBodyIcon } from './post-v1-store-body-icon';
import type { PostV1StoreBodyVersionsItem } from './post-v1-store-body-versions-item';

export type PostV1StoreBody = {
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  icon?: PostV1StoreBodyIcon;
  publisher_id: string;
  publisher_type: string;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  stage?: string | null;
  /** @nullable */
  categories?: string[] | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  public_url?: string | null;
  /** @nullable */
  published_version?: string | null;
  /** @nullable */
  versions?: PostV1StoreBodyVersionsItem[] | null;
  /** @nullable */
  is_archived?: boolean | null;
};
