/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PostNewsV1IndexingExtend200Img } from './post-news-v1-indexing-extend200-img';

/**
 * @nullable
 */
export type PostNewsV1IndexingExtend200 = {
  id: string;
  title: string;
  /** @nullable */
  description: string | null;
  url: string;
  /** @nullable */
  author: string | null;
  published_at: string;
  /** @nullable */
  source: string | null;
  /** @nullable */
  source_id: string | null;
  method: string;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  content: string | null;
  /** @nullable */
  last_checked_at: string | null;
  /** @nullable */
  img?: PostNewsV1IndexingExtend200Img;
} | null;
