/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PostCalendarV1Events200Type = typeof PostCalendarV1Events200Type[keyof typeof PostCalendarV1Events200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCalendarV1Events200Type = {
  event: 'event',
  appointment: 'appointment',
} as const;
