/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import type { PostPinsV1BoardsBoardIdAnchorsPinId502Pin } from './post-pins-v1-boards-board-id-anchors-pin-id502-pin';
import type { PostPinsV1BoardsBoardIdAnchorsPinId502Board } from './post-pins-v1-boards-board-id-anchors-pin-id502-board';
import type { PostPinsV1BoardsBoardIdAnchorsPinId502Owner } from './post-pins-v1-boards-board-id-anchors-pin-id502-owner';

/**
 * @nullable
 */
export type PostPinsV1BoardsBoardIdAnchorsPinId502 = {
  pin: PostPinsV1BoardsBoardIdAnchorsPinId502Pin;
  board: PostPinsV1BoardsBoardIdAnchorsPinId502Board;
  owner: PostPinsV1BoardsBoardIdAnchorsPinId502Owner;
} | null;
