/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PostCalendarV1SchedulesBodyMondayItem } from './post-calendar-v1-schedules-body-monday-item';
import type { PostCalendarV1SchedulesBodyTuesdayItem } from './post-calendar-v1-schedules-body-tuesday-item';
import type { PostCalendarV1SchedulesBodyWednesdayItem } from './post-calendar-v1-schedules-body-wednesday-item';
import type { PostCalendarV1SchedulesBodyThursdayItem } from './post-calendar-v1-schedules-body-thursday-item';
import type { PostCalendarV1SchedulesBodyFridayItem } from './post-calendar-v1-schedules-body-friday-item';
import type { PostCalendarV1SchedulesBodySaturdayItem } from './post-calendar-v1-schedules-body-saturday-item';
import type { PostCalendarV1SchedulesBodySundayItem } from './post-calendar-v1-schedules-body-sunday-item';

export type PostCalendarV1SchedulesBody = {
  calendar_id: string;
  monday?: PostCalendarV1SchedulesBodyMondayItem[];
  tuesday?: PostCalendarV1SchedulesBodyTuesdayItem[];
  wednesday?: PostCalendarV1SchedulesBodyWednesdayItem[];
  thursday?: PostCalendarV1SchedulesBodyThursdayItem[];
  friday?: PostCalendarV1SchedulesBodyFridayItem[];
  saturday?: PostCalendarV1SchedulesBodySaturdayItem[];
  sunday?: PostCalendarV1SchedulesBodySundayItem[];
  durations?: string[];
};
