/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PostAuthV1LoginBody = {
  email: string;
  /** @minLength 6 */
  password: string;
};
