/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PutCalendarV1SchedulesScheduleId200MondayItem } from './put-calendar-v1-schedules-schedule-id200-monday-item';
import type { PutCalendarV1SchedulesScheduleId200TuesdayItem } from './put-calendar-v1-schedules-schedule-id200-tuesday-item';
import type { PutCalendarV1SchedulesScheduleId200WednesdayItem } from './put-calendar-v1-schedules-schedule-id200-wednesday-item';
import type { PutCalendarV1SchedulesScheduleId200ThursdayItem } from './put-calendar-v1-schedules-schedule-id200-thursday-item';
import type { PutCalendarV1SchedulesScheduleId200FridayItem } from './put-calendar-v1-schedules-schedule-id200-friday-item';
import type { PutCalendarV1SchedulesScheduleId200SaturdayItem } from './put-calendar-v1-schedules-schedule-id200-saturday-item';
import type { PutCalendarV1SchedulesScheduleId200SundayItem } from './put-calendar-v1-schedules-schedule-id200-sunday-item';

export type PutCalendarV1SchedulesScheduleId200 = {
  uid: string;
  calendar_id: string;
  monday: PutCalendarV1SchedulesScheduleId200MondayItem[];
  tuesday: PutCalendarV1SchedulesScheduleId200TuesdayItem[];
  wednesday: PutCalendarV1SchedulesScheduleId200WednesdayItem[];
  thursday: PutCalendarV1SchedulesScheduleId200ThursdayItem[];
  friday: PutCalendarV1SchedulesScheduleId200FridayItem[];
  saturday: PutCalendarV1SchedulesScheduleId200SaturdayItem[];
  sunday: PutCalendarV1SchedulesScheduleId200SundayItem[];
  durations: string[];
};
