/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PutCalendarV1SlotsSlotIdBody = {
  owner_id: string;
  /** @nullable */
  updated_at: string | null;
  duration: string;
  name: string;
  /** @nullable */
  description: string | null;
};
