/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */
import type { PutCalendarV1SchedulesScheduleIdBodyMondayItem } from './put-calendar-v1-schedules-schedule-id-body-monday-item';
import type { PutCalendarV1SchedulesScheduleIdBodyTuesdayItem } from './put-calendar-v1-schedules-schedule-id-body-tuesday-item';
import type { PutCalendarV1SchedulesScheduleIdBodyWednesdayItem } from './put-calendar-v1-schedules-schedule-id-body-wednesday-item';
import type { PutCalendarV1SchedulesScheduleIdBodyThursdayItem } from './put-calendar-v1-schedules-schedule-id-body-thursday-item';
import type { PutCalendarV1SchedulesScheduleIdBodyFridayItem } from './put-calendar-v1-schedules-schedule-id-body-friday-item';
import type { PutCalendarV1SchedulesScheduleIdBodySaturdayItem } from './put-calendar-v1-schedules-schedule-id-body-saturday-item';
import type { PutCalendarV1SchedulesScheduleIdBodySundayItem } from './put-calendar-v1-schedules-schedule-id-body-sunday-item';

export type PutCalendarV1SchedulesScheduleIdBody = {
  calendar_id?: string;
  monday?: PutCalendarV1SchedulesScheduleIdBodyMondayItem[];
  tuesday?: PutCalendarV1SchedulesScheduleIdBodyTuesdayItem[];
  wednesday?: PutCalendarV1SchedulesScheduleIdBodyWednesdayItem[];
  thursday?: PutCalendarV1SchedulesScheduleIdBodyThursdayItem[];
  friday?: PutCalendarV1SchedulesScheduleIdBodyFridayItem[];
  saturday?: PutCalendarV1SchedulesScheduleIdBodySaturdayItem[];
  sunday?: PutCalendarV1SchedulesScheduleIdBodySundayItem[];
  durations?: string[];
};
