/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * api.yz13
 * YZ13 API
 * OpenAPI spec version: 0.0.0
 */

export type PutWorkspacesV1WorkspaceIdBody = {
  /** @minLength 1 */
  name?: string;
  description?: string;
  public?: boolean;
  shared_with?: string[];
  tags?: string[];
};
